function summary = run_all(options)
%RUN_ALL Execute the complete macroeconometrics pipeline from any folder.
%   SUMMARY = RUN_ALL() uses the committed FRED snapshots, generates all
%   figures, writes to the repository's standard output folders, and stops
%   on the first error.
%
%   Name-value options:
%     RefreshData    Download current FRED data instead of using snapshots.
%     GenerateFigures  Generate the committed figure and dashboard files.
%     OutputRoot     Alternative root containing data/results/figures.
%     StopOnError    Stop immediately or continue after a failed phase.

arguments
    options.RefreshData (1,1) logical = false
    options.GenerateFigures (1,1) logical = true
    options.OutputRoot (1,1) string = ""
    options.StopOnError (1,1) logical = true
end

projectRoot = string(fileparts(mfilename("fullpath")));
sourceDir = fullfile(projectRoot,"src");
scriptsDir = fullfile(projectRoot,"scripts");

originalPath = path;
pathCleanup = onCleanup(@() path(originalPath)); %#ok<NASGU>
addpath(sourceDir);
addpath(scriptsDir);

cfg = macro.projectConfig(projectRoot, ...
    RefreshData=options.RefreshData, ...
    GenerateFigures=options.GenerateFigures, ...
    OutputRoot=options.OutputRoot, ...
    StopOnError=options.StopOnError);
macro.ensureOutputDirectories(cfg);

phaseFunctions = { ...
    @import_fred_data_01; ...
    @clean_transform_data_02; ...
    @exploratory_analysis_03; ...
    @regression_model_04; ...
    @diagnostics_05; ...
    @lag_model_comparison_06; ...
    @dynamic_distributed_lag_07; ...
    @out_of_sample_forecast_08; ...
    @forecast_robustness_09; ...
    @structural_break_analysis_10; ...
    @expanding_window_forecast_11; ...
    @final_research_dashboard_12};
phaseNames = [ ...
    "FRED data import"; ...
    "Data cleaning and transformation"; ...
    "Exploratory analysis"; ...
    "OLS regression"; ...
    "Regression diagnostics"; ...
    "Lag-model comparison"; ...
    "Dynamic distributed-lag regression"; ...
    "Out-of-sample forecast"; ...
    "Forecast robustness"; ...
    "Structural-break analysis"; ...
    "Expanding-window forecast"; ...
    "Final research dashboard"];

numPhases = numel(phaseFunctions);
phaseNumber = (1:numPhases)';
functionName = strings(numPhases,1);
status = repmat("NotRun",numPhases,1);
elapsedSeconds = NaN(numPhases,1);
errorIdentifier = strings(numPhases,1);
errorMessage = strings(numPhases,1);
errors = cell(numPhases,1);
phaseOutputs = cell(numPhases,1);

pipelineStart = datetime("now");
pipelineTimer = tic;
fprintf("Running 12-phase macroeconometrics pipeline\n");
fprintf("Output root: %s\n",cfg.OutputRoot);

for phaseIndex = 1:numPhases
    phaseFunction = phaseFunctions{phaseIndex};
    functionName(phaseIndex) = string(func2str(phaseFunction));
    fprintf("[%02d/12] %s ... ",phaseIndex,phaseNames(phaseIndex));
    phaseTimer = tic;
    try
        phaseOutputs{phaseIndex} = phaseFunction(cfg);
        elapsedSeconds(phaseIndex) = toc(phaseTimer);
        status(phaseIndex) = "Succeeded";
        fprintf("succeeded in %.2f s\n",elapsedSeconds(phaseIndex));
    catch phaseError
        elapsedSeconds(phaseIndex) = toc(phaseTimer);
        status(phaseIndex) = "Failed";
        errorIdentifier(phaseIndex) = string(phaseError.identifier);
        errorMessage(phaseIndex) = string(phaseError.message);
        errors{phaseIndex} = phaseError;
        fprintf("failed in %.2f s: %s\n", ...
            elapsedSeconds(phaseIndex),phaseError.message);

        if cfg.StopOnError
            totalElapsedSeconds = toc(pipelineTimer);
            summary = buildSummary(cfg,pipelineStart,totalElapsedSeconds, ...
                phaseNumber,phaseNames,functionName,status,elapsedSeconds, ...
                errorIdentifier,errorMessage,errors,phaseOutputs);
            wrappedError = MException( ...
                "macro:runAll:Phase"+compose("%02d",phaseIndex)+"Failed", ...
                "Phase %02d (%s) failed: %s", ...
                phaseIndex,phaseNames(phaseIndex),phaseError.message);
            wrappedError = addCause(wrappedError,phaseError);
            throw(wrappedError);
        end
    end
end

totalElapsedSeconds = toc(pipelineTimer);
summary = buildSummary(cfg,pipelineStart,totalElapsedSeconds, ...
    phaseNumber,phaseNames,functionName,status,elapsedSeconds, ...
    errorIdentifier,errorMessage,errors,phaseOutputs);
fprintf("Pipeline finished in %.2f s (%d succeeded, %d failed).\n", ...
    totalElapsedSeconds,sum(status == "Succeeded"),sum(status == "Failed"));
end

function summary = buildSummary(cfg,startTime,totalElapsedSeconds, ...
        phaseNumber,phaseName,functionName,status,elapsedSeconds, ...
        errorIdentifier,errorMessage,errors,phaseOutputs)
phaseSummary = table(phaseNumber,phaseName,functionName,status, ...
    elapsedSeconds,errorIdentifier,errorMessage, ...
    'VariableNames',{'Phase','Name','Function','Status', ...
    'ElapsedSeconds','ErrorIdentifier','ErrorMessage'});
summary = struct( ...
    "Success",all(status == "Succeeded"), ...
    "StartTime",startTime, ...
    "EndTime",datetime("now"), ...
    "TotalElapsedSeconds",totalElapsedSeconds, ...
    "Configuration",cfg, ...
    "Phases",phaseSummary, ...
    "Errors",{errors}, ...
    "PhaseOutputs",{phaseOutputs});
end
