function model = estimateOLS(X,Y,options)
%ESTIMATEOLS Reproduce the project's existing manual OLS calculations.
%   MODEL = macro.estimateOLS(X,Y) uses X\Y, classical homoskedastic
%   covariance, and normal-approximation coefficient p-values. RMSE uses
%   sqrt(SSE/n), while ResidualStandardError uses sqrt(SSE/(n-k)).
%
%   CovarianceSolver may be "inverse" (the Phase 4 convention) or
%   "pseudoinverse" (the Phase 7 convention). Both are classical covariance
%   calculations and require a full-column-rank design.

arguments
    X double
    Y double
    options.CovarianceSolver (1,1) string {mustBeMember( ...
        options.CovarianceSolver,["inverse","pseudoinverse"])} = "inverse"
end

if ~ismatrix(X) || isempty(X) || ~isreal(X) || any(~isfinite(X),"all")
    error("macro:estimateOLS:InvalidDesign", ...
        "X must be a nonempty, finite, real numeric matrix.");
end
if ~isvector(Y) || isempty(Y) || ~isreal(Y) || any(~isfinite(Y),"all")
    error("macro:estimateOLS:InvalidResponse", ...
        "Y must be a nonempty, finite, real numeric vector.");
end

Y = Y(:);
[numObservations,numParameters] = size(X);
if numel(Y) ~= numObservations
    error("macro:estimateOLS:DimensionMismatch", ...
        "X and Y must contain the same number of observations.");
end
if numObservations <= numParameters
    error("macro:estimateOLS:InsufficientDegreesOfFreedom", ...
        ["OLS requires more observations than parameters; received " + ...
         "%d observations and %d parameters."], ...
        numObservations,numParameters);
end
if numParameters < 2
    error("macro:estimateOLS:InsufficientPredictors", ...
        "The project F-statistic convention requires an intercept and predictor.");
end
if rank(X) < numParameters
    error("macro:estimateOLS:RankDeficientDesign", ...
        ["Design matrix is rank deficient (%d columns, rank %d). " + ...
         "OLS statistics would not be uniquely identified."], ...
        numParameters,rank(X));
end

coefficients = X \ Y;
fitted = X * coefficients;
residuals = Y - fitted;

degreesFreedom = numObservations - numParameters;
SSE = sum(residuals.^2);
SST = sum((Y-mean(Y)).^2);
if SST == 0
    error("macro:estimateOLS:ConstantResponse", ...
        "R-squared is undefined when Y has no variation.");
end
SSR = SST - SSE;

RSquared = 1 - SSE/SST;
AdjustedRSquared = 1 - ((SSE/degreesFreedom)/(SST/(numObservations-1)));
RMSE = sqrt(mean(residuals.^2));
residualVariance = SSE/degreesFreedom;
residualStandardError = sqrt(residualVariance);
FStatistic = (SSR/(numParameters-1))/(SSE/degreesFreedom);

logLikelihood = -numObservations/2 * ...
    (log(2*pi)+1+log(SSE/numObservations));
AIC = 2*numParameters - 2*logLikelihood;
BIC = log(numObservations)*numParameters - 2*logLikelihood;

crossProduct = X' * X;
switch options.CovarianceSolver
    case "inverse"
        covariance = residualVariance * inv(crossProduct); %#ok<MINV>
    case "pseudoinverse"
        covariance = residualVariance * pinv(crossProduct);
end
standardErrors = sqrt(diag(covariance));
tStatistics = coefficients ./ standardErrors;
approxPValues = erfc(abs(tStatistics)/sqrt(2));

model = struct( ...
    "Coefficients",coefficients, ...
    "Fitted",fitted, ...
    "Residuals",residuals, ...
    "Observations",numObservations, ...
    "Parameters",numParameters, ...
    "DegreesFreedom",degreesFreedom, ...
    "SSE",SSE, ...
    "SST",SST, ...
    "SSR",SSR, ...
    "RSquared",RSquared, ...
    "AdjustedRSquared",AdjustedRSquared, ...
    "RMSE",RMSE, ...
    "ResidualVariance",residualVariance, ...
    "ResidualStandardError",residualStandardError, ...
    "FStatistic",FStatistic, ...
    "LogLikelihood",logLikelihood, ...
    "AIC",AIC, ...
    "BIC",BIC, ...
    "Covariance",covariance, ...
    "StandardErrors",standardErrors, ...
    "TStatistics",tStatistics, ...
    "ApproxPValues",approxPValues, ...
    "CovarianceSolver",options.CovarianceSolver);
end
