function metrics = forecastMetrics(actual,forecast,persistenceForecast)
%FORECASTMETRICS Reproduce the project's existing forecast calculations.
%   Directional accuracy compares sign(forecast) with sign(actual), exactly
%   as in Phases 8 and 11. Improvements are percentage reductions in RMSE
%   and MAE relative to the supplied persistence forecast.

arguments
    actual double
    forecast double
    persistenceForecast double
end

actual = validateSeries(actual,"actual");
forecast = validateSeries(forecast,"forecast");
persistenceForecast = validateSeries( ...
    persistenceForecast,"persistence forecast");

if numel(forecast) ~= numel(actual) || ...
        numel(persistenceForecast) ~= numel(actual)
    error("macro:forecastMetrics:DimensionMismatch", ...
        "Actual, forecast, and persistence series must have equal lengths.");
end
if numel(actual) < 2
    error("macro:forecastMetrics:InsufficientObservations", ...
        "At least two observations are required for forecast correlation.");
end

errors = actual - forecast;
persistenceErrors = actual - persistenceForecast;

RMSE = sqrt(mean(errors.^2));
MAE = mean(abs(errors));
forecastCorrelation = corr(actual,forecast);
directionalAccuracy = mean(sign(forecast) == sign(actual))*100;

persistenceRMSE = sqrt(mean(persistenceErrors.^2));
persistenceMAE = mean(abs(persistenceErrors));
RMSEImprovementPercent = ...
    ((persistenceRMSE-RMSE)/persistenceRMSE)*100;
MAEImprovementPercent = ...
    ((persistenceMAE-MAE)/persistenceMAE)*100;

metrics = struct( ...
    "Errors",errors, ...
    "PersistenceErrors",persistenceErrors, ...
    "RMSE",RMSE, ...
    "MAE",MAE, ...
    "Correlation",forecastCorrelation, ...
    "ForecastCorrelation",forecastCorrelation, ...
    "DirectionalAccuracy",directionalAccuracy, ...
    "DirectionalAccuracyPercent",directionalAccuracy, ...
    "PersistenceRMSE",persistenceRMSE, ...
    "PersistenceMAE",persistenceMAE, ...
    "NaiveRMSE",persistenceRMSE, ...
    "NaiveMAE",persistenceMAE, ...
    "RMSEImprovementPercent",RMSEImprovementPercent, ...
    "MAEImprovementPercent",MAEImprovementPercent);
end

function values = validateSeries(values,seriesName)
if ~isvector(values) || isempty(values) || ~isreal(values) || ...
        any(~isfinite(values),"all")
    error("macro:forecastMetrics:InvalidSeries", ...
        "%s must be a nonempty, finite, real numeric vector.",seriesName);
end
values = values(:);
end
