function output = dynamic_distributed_lag_07(cfg)
%DYNAMIC_DISTRIBUTED_LAG_07 Phase 7 - Dynamic distributed-lag model.

if nargin < 1
    cfg = [];
end
[cfg,pathCleanup] = initializePhaseConfiguration( ...
    cfg,mfilename("fullpath")); %#ok<ASGLU>

clc;
close all;

%% MATLAB MACROECONOMETRICS PROJECT
% Phase 7 - Dynamic Distributed Lag Model

disp("==============================================");
disp(" MATLAB MACROECONOMETRICS PROJECT");
disp(" Phase 7: Dynamic Distributed Lag Regression");
disp("==============================================");

macro.ensureOutputDirectories(cfg);

%% Load cleaned quarterly dataset

DATA = readtimetable( ...
    resolveDataInput(cfg,"Macroeconomic_Data_Quarterly.csv"));

DATA = macro.validateQuarterlyData(DATA);

disp("Dataset loaded successfully.");

%% Build and estimate the exact Phase 7 specification

design = macro.buildDynamicDesign(DATA);
MODEL = macro.estimateOLS(design.X,design.Y, ...
    CovarianceSolver="pseudoinverse");

Y = design.Y;
dates = design.Dates;
X = design.X;
beta = MODEL.Coefficients;
Y_hat = MODEL.Fitted;
residuals = MODEL.Residuals;
n = MODEL.Observations;
k = MODEL.Parameters;
SSE = MODEL.SSE;
SST = MODEL.SST;
SSR = MODEL.SSR;
R2 = MODEL.RSquared;
AdjustedR2 = MODEL.AdjustedRSquared;
RMSE = MODEL.RMSE;
FStatistic = MODEL.FStatistic;
logLik = MODEL.LogLikelihood;
AIC = MODEL.AIC;
BIC = MODEL.BIC;
sigma2 = MODEL.ResidualVariance;
VarBeta = MODEL.Covariance;
SE = MODEL.StandardErrors;
TStatistic = MODEL.TStatistics;
ApproxPValue = MODEL.ApproxPValues;

%% Variable names

Variable = design.VariableNames';

%% Coefficient table

DYNAMIC_RESULTS = table( ...
    Variable, ...
    beta, ...
    SE, ...
    TStatistic, ...
    ApproxPValue, ...
    'VariableNames', ...
    {'Variable', ...
     'Coefficient', ...
     'StandardError', ...
     'TStatistic', ...
     'ApproxPValue'});

disp(" ");
disp("==============================================");
disp(" DYNAMIC MODEL COEFFICIENTS");
disp("==============================================");

disp(DYNAMIC_RESULTS);

%% Display model performance

fprintf("\nObservations: %d\n",n);
fprintf("R-Squared: %.4f\n",R2);
fprintf("Adjusted R-Squared: %.4f\n",AdjustedR2);
fprintf("RMSE: %.4f\n",RMSE);
fprintf("F-Statistic: %.4f\n",FStatistic);
fprintf("AIC: %.2f\n",AIC);
fprintf("BIC: %.2f\n",BIC);

%% Save model coefficients

writetable( ...
    DYNAMIC_RESULTS, ...
    fullfile( ...
        cfg.ResultsDir, ...
        "Dynamic_Distributed_Lag_Results.csv"));

%% Model summary

MODEL_SUMMARY = table( ...
    n, ...
    R2, ...
    AdjustedR2, ...
    RMSE, ...
    FStatistic, ...
    AIC, ...
    BIC, ...
    'VariableNames', ...
    {'Observations', ...
     'RSquared', ...
     'AdjustedRSquared', ...
     'RMSE', ...
     'FStatistic', ...
     'AIC', ...
     'BIC'});

writetable( ...
    MODEL_SUMMARY, ...
    fullfile( ...
        cfg.ResultsDir, ...
        "Dynamic_Model_Summary.csv"));

%% Prediction output

PREDICTIONS = table( ...
    dates, ...
    Y, ...
    Y_hat, ...
    residuals, ...
    'VariableNames', ...
    {'Date', ...
     'ActualGDPGrowth', ...
     'PredictedGDPGrowth', ...
     'Residual'});

writetable( ...
    PREDICTIONS, ...
    fullfile( ...
        cfg.ResultsDir, ...
        "Dynamic_Model_Predictions.csv"));

%% Figure 19 - Actual vs predicted

if cfg.GenerateFigures

fig1 = figure( ...
    'Position',[100 100 1200 650]);

plot( ...
    dates, ...
    Y, ...
    'LineWidth',1.5);

hold on;

plot( ...
    dates, ...
    Y_hat, ...
    '--', ...
    'LineWidth',1.6);

yline(0,'--');

grid on;

title( ...
    "Dynamic Distributed-Lag Model");

subtitle( ...
    "Actual vs Predicted U.S. Real GDP Growth");

xlabel("Year");
ylabel("Annualized GDP Growth (%)");

legend( ...
    "Actual GDP Growth", ...
    "Predicted GDP Growth", ...
    'Location','best');

hold off;

exportgraphics( ...
    fig1, ...
    fullfile( ...
        cfg.FiguresDir, ...
        "19_Dynamic_Model_Actual_vs_Predicted.png"), ...
    'Resolution',300);

%% Figure 20 - Inflation lag effects

fig2 = figure;

inflationEffects = ...
    beta(3:7);

plot( ...
    0:4, ...
    inflationEffects, ...
    '-o', ...
    'LineWidth',1.8);

yline(0,'--');

grid on;

title("Dynamic Response: Inflation Coefficients");

xlabel("Lag (Quarters)");
ylabel("Estimated Coefficient");

exportgraphics( ...
    fig2, ...
    fullfile( ...
        cfg.FiguresDir, ...
        "20_Inflation_Lag_Effects.png"), ...
    'Resolution',300);

%% Figure 21 - Unemployment lag effects

fig3 = figure;

unemploymentEffects = ...
    beta(8:12);

plot( ...
    0:4, ...
    unemploymentEffects, ...
    '-o', ...
    'LineWidth',1.8);

yline(0,'--');

grid on;

title("Dynamic Response: Unemployment Coefficients");

xlabel("Lag (Quarters)");
ylabel("Estimated Coefficient");

exportgraphics( ...
    fig3, ...
    fullfile( ...
        cfg.FiguresDir, ...
        "21_Unemployment_Lag_Effects.png"), ...
    'Resolution',300);

%% Figure 22 - Interest rate lag effects

fig4 = figure;

rateEffects = ...
    beta(13:17);

plot( ...
    0:4, ...
    rateEffects, ...
    '-o', ...
    'LineWidth',1.8);

yline(0,'--');

grid on;

title("Dynamic Response: Interest Rate Coefficients");

xlabel("Lag (Quarters)");
ylabel("Estimated Coefficient");

exportgraphics( ...
    fig4, ...
    fullfile( ...
        cfg.FiguresDir, ...
        "22_Interest_Rate_Lag_Effects.png"), ...
    'Resolution',300);

end

%% Finish

disp(" ");
disp("==============================================");
disp(" PHASE 7 COMPLETE");
disp("==============================================");

disp("Dynamic regression completed successfully.");
disp("Outputs saved to results and figures folders.");

output = struct("Design",design, ...
    "Model",MODEL, ...
    "DynamicResults",DYNAMIC_RESULTS, ...
    "ModelSummary",MODEL_SUMMARY, ...
    "Predictions",PREDICTIONS, ...
    "FigureFiles",[ ...
        "19_Dynamic_Model_Actual_vs_Predicted.png"; ...
        "20_Inflation_Lag_Effects.png"; ...
        "21_Unemployment_Lag_Effects.png"; ...
        "22_Interest_Rate_Lag_Effects.png"]);
end

function [cfg,pathCleanup] = initializePhaseConfiguration(cfg,scriptPath)
projectRoot = string(fileparts(fileparts(scriptPath)));
sourceDir = fullfile(projectRoot,"src");
pathEntries = string(strsplit(path,pathsep));
if ~any(pathEntries == sourceDir)
    addpath(sourceDir);
    pathCleanup = onCleanup(@() rmpath(sourceDir));
else
    pathCleanup = onCleanup(@() []);
end
if isempty(cfg)
    cfg = macro.projectConfig(projectRoot);
end
end

function inputFile = resolveDataInput(cfg,fileName)
inputFile = fullfile(cfg.DataDir,fileName);
if ~isfile(inputFile)
    sourceFile = fullfile(cfg.SourceDataDir,fileName);
    if ~isfile(sourceFile)
        error("macro:phase07:MissingInput", ...
            "Required processed-data file was not found: %s",fileName);
    end
    inputFile = sourceFile;
end
end
