clc;
clear;
close all;

%% MATLAB MACROECONOMETRICS PROJECT
% Phase 11 - Expanding Window Forecasting
%
% Objective:
% Re-estimate the forecasting model every quarter using
% all information available up to that point.
%
% Compare:
% 1. Fixed historical model
% 2. Expanding-window adaptive model
% 3. Naive persistence benchmark

disp("==============================================");
disp(" MATLAB MACROECONOMETRICS PROJECT");
disp(" Phase 11: Expanding Window Forecasting");
disp("==============================================");

%% Load cleaned quarterly dataset

DATA = readtimetable( ...
    fullfile("data","Macroeconomic_Data_Quarterly.csv"));

disp("Quarterly dataset loaded successfully.");

%% ---------------------------------------------------------
% Build forecast-ready lagged dataset
% ----------------------------------------------------------

maxLag = 4;

GDP   = DATA.GDPGrowth;
INF   = DATA.Inflation;
UNEMP = DATA.Unemployment;
RATE  = DATA.InterestRate;
DATES = DATA.observation_date;

%% Response variable

Y = GDP(maxLag+1:end);
forecastDates = DATES(maxLag+1:end);

%% Lagged GDP growth

GDP_L1 = GDP(maxLag:end-1);

%% Inflation lags

INF_L1 = INF(maxLag:end-1);
INF_L2 = INF(maxLag-1:end-2);
INF_L3 = INF(maxLag-2:end-3);
INF_L4 = INF(maxLag-3:end-4);

%% Unemployment lags

UNEMP_L1 = UNEMP(maxLag:end-1);
UNEMP_L2 = UNEMP(maxLag-1:end-2);
UNEMP_L3 = UNEMP(maxLag-2:end-3);
UNEMP_L4 = UNEMP(maxLag-3:end-4);

%% Interest-rate lags

RATE_L1 = RATE(maxLag:end-1);
RATE_L2 = RATE(maxLag-1:end-2);
RATE_L3 = RATE(maxLag-2:end-3);
RATE_L4 = RATE(maxLag-3:end-4);

%% Predictor matrix

X = [ ...
    ones(length(Y),1), ...
    GDP_L1, ...
    INF_L1, INF_L2, INF_L3, INF_L4, ...
    UNEMP_L1, UNEMP_L2, UNEMP_L3, UNEMP_L4, ...
    RATE_L1, RATE_L2, RATE_L3, RATE_L4];

%% ---------------------------------------------------------
% Define out-of-sample test period
% ----------------------------------------------------------

splitDate = datetime(2016,1,1);

trainInitial = forecastDates < splitDate;
testIndex = forecastDates >= splitDate;

testRows = find(testIndex);

Y_test = Y(testIndex);
datesTest = forecastDates(testIndex);

numForecasts = length(Y_test);

fprintf("\nInitial training observations: %d\n",sum(trainInitial));
fprintf("Out-of-sample forecasts: %d\n",numForecasts);

%% ---------------------------------------------------------
% FIXED MODEL
% Estimate once using data before 2016
% ----------------------------------------------------------

X_initial = X(trainInitial,:);
Y_initial = Y(trainInitial);

betaFixed = X_initial \ Y_initial;

FixedForecast = X(testIndex,:) * betaFixed;

%% ---------------------------------------------------------
% EXPANDING WINDOW MODEL
% Re-estimate model before every forecast
% ----------------------------------------------------------

ExpandingForecast = zeros(numForecasts,1);

CoefficientHistory = zeros( ...
    numForecasts, ...
    size(X,2));

TrainingSize = zeros(numForecasts,1);

for i = 1:numForecasts

    currentRow = testRows(i);

    % Use all observations strictly before forecast quarter
    trainingRows = 1:(currentRow-1);

    X_train = X(trainingRows,:);
    Y_train = Y(trainingRows);

    % Re-estimate coefficients
    betaAdaptive = X_train \ Y_train;

    % Generate one-step-ahead prediction
    ExpandingForecast(i) = ...
        X(currentRow,:) * betaAdaptive;

    % Save coefficient history
    CoefficientHistory(i,:) = betaAdaptive';

    TrainingSize(i) = length(Y_train);

end

%% ---------------------------------------------------------
% NAIVE BENCHMARK
% Previous quarter's GDP growth
% ----------------------------------------------------------

NaiveForecast = GDP_L1(testIndex);

%% ---------------------------------------------------------
% Forecast errors
% ----------------------------------------------------------

FixedError = Y_test - FixedForecast;

ExpandingError = ...
    Y_test - ExpandingForecast;

NaiveError = Y_test - NaiveForecast;

%% ---------------------------------------------------------
% Performance metrics
% ----------------------------------------------------------

FixedRMSE = ...
    sqrt(mean(FixedError.^2));

ExpandingRMSE = ...
    sqrt(mean(ExpandingError.^2));

NaiveRMSE = ...
    sqrt(mean(NaiveError.^2));

FixedMAE = ...
    mean(abs(FixedError));

ExpandingMAE = ...
    mean(abs(ExpandingError));

NaiveMAE = ...
    mean(abs(NaiveError));

%% Forecast correlation

FixedCorrelation = ...
    corr(Y_test,FixedForecast);

ExpandingCorrelation = ...
    corr(Y_test,ExpandingForecast);

NaiveCorrelation = ...
    corr(Y_test,NaiveForecast);

%% Directional accuracy

ActualDirection = sign(Y_test);

FixedDirectionalAccuracy = ...
    mean(sign(FixedForecast) == ...
    ActualDirection) * 100;

ExpandingDirectionalAccuracy = ...
    mean(sign(ExpandingForecast) == ...
    ActualDirection) * 100;

NaiveDirectionalAccuracy = ...
    mean(sign(NaiveForecast) == ...
    ActualDirection) * 100;

%% Improvement against naive benchmark

FixedRMSEImprovement = ...
    ((NaiveRMSE-FixedRMSE) / ...
    NaiveRMSE) * 100;

ExpandingRMSEImprovement = ...
    ((NaiveRMSE-ExpandingRMSE) / ...
    NaiveRMSE) * 100;

FixedMAEImprovement = ...
    ((NaiveMAE-FixedMAE) / ...
    NaiveMAE) * 100;

ExpandingMAEImprovement = ...
    ((NaiveMAE-ExpandingMAE) / ...
    NaiveMAE) * 100;

%% ---------------------------------------------------------
% Performance leaderboard
% ----------------------------------------------------------

Model = [ ...
    "Fixed Historical Model"
    "Expanding Window Model"
    "Naive Persistence"
    ];

RMSE = [ ...
    FixedRMSE
    ExpandingRMSE
    NaiveRMSE
    ];

MAE = [ ...
    FixedMAE
    ExpandingMAE
    NaiveMAE
    ];

Correlation = [ ...
    FixedCorrelation
    ExpandingCorrelation
    NaiveCorrelation
    ];

DirectionalAccuracy = [ ...
    FixedDirectionalAccuracy
    ExpandingDirectionalAccuracy
    NaiveDirectionalAccuracy
    ];

MODEL_LEADERBOARD = table( ...
    Model, ...
    RMSE, ...
    MAE, ...
    Correlation, ...
    DirectionalAccuracy);

disp(" ");
disp("==============================================");
disp(" EXPANDING WINDOW MODEL LEADERBOARD");
disp("==============================================");

disp(MODEL_LEADERBOARD);

fprintf("\nFixed RMSE Improvement vs Naive: %.2f %%\n", ...
    FixedRMSEImprovement);

fprintf("Expanding RMSE Improvement vs Naive: %.2f %%\n", ...
    ExpandingRMSEImprovement);

fprintf("\nFixed MAE Improvement vs Naive: %.2f %%\n", ...
    FixedMAEImprovement);

fprintf("Expanding MAE Improvement vs Naive: %.2f %%\n", ...
    ExpandingMAEImprovement);

%% Save leaderboard

writetable( ...
    MODEL_LEADERBOARD, ...
    fullfile( ...
        "results", ...
        "Expanding_Window_Model_Leaderboard.csv"));

%% ---------------------------------------------------------
% Save forecast results
% ----------------------------------------------------------

FORECAST_RESULTS = table( ...
    datesTest, ...
    Y_test, ...
    FixedForecast, ...
    ExpandingForecast, ...
    NaiveForecast, ...
    FixedError, ...
    ExpandingError, ...
    NaiveError, ...
    TrainingSize, ...
    'VariableNames', ...
    {'Date', ...
     'ActualGDPGrowth', ...
     'FixedForecast', ...
     'ExpandingForecast', ...
     'NaiveForecast', ...
     'FixedError', ...
     'ExpandingError', ...
     'NaiveError', ...
     'TrainingSize'});

writetable( ...
    FORECAST_RESULTS, ...
    fullfile( ...
        "results", ...
        "Expanding_Window_Forecasts.csv"));

%% ---------------------------------------------------------
% Coefficient history
% ----------------------------------------------------------

VariableNames = { ...
    'Intercept', ...
    'GDPGrowth_L1', ...
    'Inflation_L1', ...
    'Inflation_L2', ...
    'Inflation_L3', ...
    'Inflation_L4', ...
    'Unemployment_L1', ...
    'Unemployment_L2', ...
    'Unemployment_L3', ...
    'Unemployment_L4', ...
    'InterestRate_L1', ...
    'InterestRate_L2', ...
    'InterestRate_L3', ...
    'InterestRate_L4'};

COEFFICIENT_HISTORY = array2table( ...
    CoefficientHistory, ...
    'VariableNames', ...
    VariableNames);

COEFFICIENT_HISTORY.Date = datesTest;

COEFFICIENT_HISTORY = ...
    movevars( ...
        COEFFICIENT_HISTORY, ...
        "Date", ...
        "Before", ...
        1);

writetable( ...
    COEFFICIENT_HISTORY, ...
    fullfile( ...
        "results", ...
        "Expanding_Window_Coefficient_History.csv"));

%% ---------------------------------------------------------
% Rolling RMSE
% ----------------------------------------------------------

rollingWindow = 8;

RollingFixedRMSE = ...
    NaN(numForecasts,1);

RollingExpandingRMSE = ...
    NaN(numForecasts,1);

RollingNaiveRMSE = ...
    NaN(numForecasts,1);

for i = rollingWindow:numForecasts

    idx = ...
        (i-rollingWindow+1):i;

    RollingFixedRMSE(i) = ...
        sqrt(mean(FixedError(idx).^2));

    RollingExpandingRMSE(i) = ...
        sqrt(mean(ExpandingError(idx).^2));

    RollingNaiveRMSE(i) = ...
        sqrt(mean(NaiveError(idx).^2));

end

%% ---------------------------------------------------------
% Figure 34 - Actual vs all forecasts
% ----------------------------------------------------------

fig1 = figure( ...
    'Position',[100 100 1250 650]);

plot( ...
    datesTest, ...
    Y_test, ...
    'LineWidth',1.7);

hold on;

plot( ...
    datesTest, ...
    FixedForecast, ...
    '--', ...
    'LineWidth',1.4);

plot( ...
    datesTest, ...
    ExpandingForecast, ...
    '-.', ...
    'LineWidth',1.5);

plot( ...
    datesTest, ...
    NaiveForecast, ...
    ':', ...
    'LineWidth',1.4);

xline( ...
    datetime(2020,1,1), ...
    '--', ...
    '2020 Shock');

yline(0,'--');

grid on;

title("Adaptive Out-of-Sample GDP Growth Forecasting");

subtitle( ...
    "Fixed Model vs Expanding Window vs Naive Persistence");

xlabel("Year");
ylabel("Annualized GDP Growth (%)");

legend( ...
    "Actual GDP Growth", ...
    "Fixed Historical Model", ...
    "Expanding Window Model", ...
    "Naive Persistence", ...
    'Location','best');

hold off;

exportgraphics( ...
    fig1, ...
    fullfile( ...
        "figures", ...
        "34_Adaptive_Forecast_Comparison.png"), ...
    'Resolution',300);

%% ---------------------------------------------------------
% Figure 35 - Rolling RMSE
% ----------------------------------------------------------

fig2 = figure( ...
    'Position',[100 100 1250 650]);

plot( ...
    datesTest, ...
    RollingFixedRMSE, ...
    'LineWidth',1.5);

hold on;

plot( ...
    datesTest, ...
    RollingExpandingRMSE, ...
    'LineWidth',1.6);

plot( ...
    datesTest, ...
    RollingNaiveRMSE, ...
    'LineWidth',1.5);

xline( ...
    datetime(2020,1,1), ...
    '--', ...
    '2020 Shock');

grid on;

title("Rolling Forecast RMSE");

subtitle("Eight-Quarter Forecast Error Window");

xlabel("Year");
ylabel("Rolling RMSE");

legend( ...
    "Fixed Historical Model", ...
    "Expanding Window Model", ...
    "Naive Persistence", ...
    'Location','best');

hold off;

exportgraphics( ...
    fig2, ...
    fullfile( ...
        "figures", ...
        "35_Rolling_RMSE.png"), ...
    'Resolution',300);

%% ---------------------------------------------------------
% Figure 36 - Model leaderboard
% ----------------------------------------------------------

fig3 = figure( ...
    'Position',[100 100 950 600]);

bar( ...
    categorical(Model), ...
    RMSE);

grid on;

title("Out-of-Sample Forecast Model Leaderboard");

subtitle("Lower RMSE Indicates Better Forecast Performance");

ylabel("RMSE");

exportgraphics( ...
    fig3, ...
    fullfile( ...
        "figures", ...
        "36_Forecast_Model_Leaderboard.png"), ...
    'Resolution',300);

%% ---------------------------------------------------------
% Figure 37 - Coefficient evolution
% Selected economically important coefficients
% ----------------------------------------------------------

fig4 = figure( ...
    'Position',[100 100 1250 650]);

plot( ...
    datesTest, ...
    CoefficientHistory(:,2), ...
    'LineWidth',1.5);

hold on;

plot( ...
    datesTest, ...
    CoefficientHistory(:,7), ...
    'LineWidth',1.5);

plot( ...
    datesTest, ...
    CoefficientHistory(:,11), ...
    'LineWidth',1.5);

xline( ...
    datetime(2020,1,1), ...
    '--', ...
    '2020 Shock');

yline(0,'--');

grid on;

title("Evolution of Expanding-Window Coefficients");

subtitle("Adaptive Model Parameter Stability");

xlabel("Year");
ylabel("Estimated Coefficient");

legend( ...
    "GDP Growth Lag 1", ...
    "Unemployment Lag 1", ...
    "Interest Rate Lag 1", ...
    'Location','best');

hold off;

exportgraphics( ...
    fig4, ...
    fullfile( ...
        "figures", ...
        "37_Adaptive_Coefficient_Evolution.png"), ...
    'Resolution',300);

%% ---------------------------------------------------------
% Figure 38 - Cumulative absolute forecast error
% ----------------------------------------------------------

CumulativeFixedError = ...
    cumsum(abs(FixedError));

CumulativeExpandingError = ...
    cumsum(abs(ExpandingError));

CumulativeNaiveError = ...
    cumsum(abs(NaiveError));

fig5 = figure( ...
    'Position',[100 100 1250 650]);

plot( ...
    datesTest, ...
    CumulativeFixedError, ...
    'LineWidth',1.5);

hold on;

plot( ...
    datesTest, ...
    CumulativeExpandingError, ...
    'LineWidth',1.6);

plot( ...
    datesTest, ...
    CumulativeNaiveError, ...
    'LineWidth',1.5);

xline( ...
    datetime(2020,1,1), ...
    '--', ...
    '2020 Shock');

grid on;

title("Cumulative Absolute Forecast Error");

subtitle("Long-Run Forecast Performance Comparison");

xlabel("Year");
ylabel("Cumulative Absolute Error");

legend( ...
    "Fixed Historical Model", ...
    "Expanding Window Model", ...
    "Naive Persistence", ...
    'Location','best');

hold off;

exportgraphics( ...
    fig5, ...
    fullfile( ...
        "figures", ...
        "38_Cumulative_Forecast_Error.png"), ...
    'Resolution',300);

%% Finish

disp(" ");
disp("==============================================");
disp(" PHASE 11 COMPLETE");
disp("==============================================");

disp("Results saved:");
disp("results/Expanding_Window_Model_Leaderboard.csv");
disp("results/Expanding_Window_Forecasts.csv");
disp("results/Expanding_Window_Coefficient_History.csv");

disp(" ");

disp("Figures saved:");
disp("figures/34_Adaptive_Forecast_Comparison.png");
disp("figures/35_Rolling_RMSE.png");
disp("figures/36_Forecast_Model_Leaderboard.png");
disp("figures/37_Adaptive_Coefficient_Evolution.png");
disp("figures/38_Cumulative_Forecast_Error.png");