clc;
clear;
close all;

%% MATLAB MACROECONOMETRICS PROJECT
% Phase 9 - Forecast Robustness Across Economic Regimes

disp("==============================================");
disp(" MATLAB MACROECONOMETRICS PROJECT");
disp(" Phase 9: Forecast Robustness Analysis");
disp("==============================================");

%% Load previously generated forecasts

RESULTS = readtable( ...
    fullfile("results","Out_of_Sample_Forecasts.csv"));

%% Convert date variable

RESULTS.Date = datetime(RESULTS.Date);

%% Extract variables

dates = RESULTS.Date;

actual = RESULTS.ActualGDPGrowth;
modelForecast = RESULTS.EconometricForecast;
naiveForecast = RESULTS.NaiveForecast;

%% Define economic regimes

preCovid = ...
    dates < datetime(2020,1,1);

covidShock = ...
    dates >= datetime(2020,1,1) & ...
    dates < datetime(2021,1,1);

postCovid = ...
    dates >= datetime(2021,1,1);

%% ---------------------------------------------------------
% Helper calculations
% ----------------------------------------------------------

regimeNames = [ ...
    "2016-2019 Pre-COVID"
    "2020 COVID Shock"
    "2021+ Post-COVID"
    "Full Test Sample"
    ];

indices = { ...
    preCovid
    covidShock
    postCovid
    true(size(dates))
    };

numRegimes = length(regimeNames);

ModelRMSE = zeros(numRegimes,1);
NaiveRMSE = zeros(numRegimes,1);

ModelMAE = zeros(numRegimes,1);
NaiveMAE = zeros(numRegimes,1);

RMSEImprovement = zeros(numRegimes,1);
MAEImprovement = zeros(numRegimes,1);

Observations = zeros(numRegimes,1);

%% Calculate metrics for each regime

for r = 1:numRegimes

    idx = indices{r};

    y = actual(idx);

    model = modelForecast(idx);
    naive = naiveForecast(idx);

    modelError = y - model;
    naiveError = y - naive;

    Observations(r) = sum(idx);

    ModelRMSE(r) = ...
        sqrt(mean(modelError.^2));

    NaiveRMSE(r) = ...
        sqrt(mean(naiveError.^2));

    ModelMAE(r) = ...
        mean(abs(modelError));

    NaiveMAE(r) = ...
        mean(abs(naiveError));

    RMSEImprovement(r) = ...
        ((NaiveRMSE(r) - ModelRMSE(r)) ...
        / NaiveRMSE(r)) * 100;

    MAEImprovement(r) = ...
        ((NaiveMAE(r) - ModelMAE(r)) ...
        / NaiveMAE(r)) * 100;

end

%% Build robustness table

ROBUSTNESS = table( ...
    regimeNames, ...
    Observations, ...
    ModelRMSE, ...
    NaiveRMSE, ...
    RMSEImprovement, ...
    ModelMAE, ...
    NaiveMAE, ...
    MAEImprovement, ...
    'VariableNames', ...
    {'Regime', ...
     'Observations', ...
     'ModelRMSE', ...
     'NaiveRMSE', ...
     'RMSEImprovementPercent', ...
     'ModelMAE', ...
     'NaiveMAE', ...
     'MAEImprovementPercent'});

disp(" ");
disp("==============================================");
disp(" FORECAST ROBUSTNESS RESULTS");
disp("==============================================");

disp(ROBUSTNESS);

%% Save results

writetable( ...
    ROBUSTNESS, ...
    fullfile( ...
        "results", ...
        "Forecast_Robustness_Results.csv"));

%% Figure 27 - RMSE by regime

fig1 = figure( ...
    'Position',[100 100 1200 650]);

bar( ...
    categorical(regimeNames), ...
    [ModelRMSE NaiveRMSE]);

grid on;

title("Forecast RMSE Across Economic Regimes");

subtitle( ...
    "Econometric Model vs Naive Benchmark");

ylabel("RMSE");

legend( ...
    "Econometric Model", ...
    "Naive Benchmark", ...
    'Location','best');

exportgraphics( ...
    fig1, ...
    fullfile( ...
        "figures", ...
        "27_Forecast_RMSE_by_Regime.png"), ...
    'Resolution',300);

%% Figure 28 - MAE by regime

fig2 = figure( ...
    'Position',[100 100 1200 650]);

bar( ...
    categorical(regimeNames), ...
    [ModelMAE NaiveMAE]);

grid on;

title("Forecast MAE Across Economic Regimes");

subtitle( ...
    "Sensitivity of Forecast Performance to Structural Shocks");

ylabel("MAE");

legend( ...
    "Econometric Model", ...
    "Naive Benchmark", ...
    'Location','best');

exportgraphics( ...
    fig2, ...
    fullfile( ...
        "figures", ...
        "28_Forecast_MAE_by_Regime.png"), ...
    'Resolution',300);

%% Figure 29 - Actual vs forecasts with COVID markers

fig3 = figure( ...
    'Position',[100 100 1250 650]);

plot( ...
    dates, ...
    actual, ...
    'LineWidth',1.6);

hold on;

plot( ...
    dates, ...
    modelForecast, ...
    '--', ...
    'LineWidth',1.5);

plot( ...
    dates, ...
    naiveForecast, ...
    ':', ...
    'LineWidth',1.5);

xline( ...
    datetime(2020,1,1), ...
    '--', ...
    'COVID-19 Shock Begins');

xline( ...
    datetime(2021,1,1), ...
    '--', ...
    'Post-COVID Period');

yline(0,'--');

grid on;

title("Forecast Performance Through the COVID-19 Structural Shock");

xlabel("Year");
ylabel("Annualized GDP Growth (%)");

legend( ...
    "Actual GDP Growth", ...
    "Econometric Forecast", ...
    "Naive Benchmark", ...
    'Location','best');

hold off;

exportgraphics( ...
    fig3, ...
    fullfile( ...
        "figures", ...
        "29_Forecasts_and_COVID_Shock.png"), ...
    'Resolution',300);

%% Finish

disp(" ");
disp("==============================================");
disp(" PHASE 9 COMPLETE");
disp("==============================================");

disp("Result saved:");
disp("results/Forecast_Robustness_Results.csv");

disp(" ");

disp("Figures saved:");
disp("figures/27_Forecast_RMSE_by_Regime.png");
disp("figures/28_Forecast_MAE_by_Regime.png");
disp("figures/29_Forecasts_and_COVID_Shock.png");