function design = buildCommonSampleLagDesign(data,lag,options)
%BUILDCOMMONSAMPLELAGDESIGN Build an equal-response-sample lag design.
%   All candidate lags share response rows MaximumLag+1 through n. For a
%   candidate lag L, predictors come from response row minus L. Lag zero is
%   explicitly contemporaneous; positive lags are strictly pre-response.

arguments
    data
    lag (1,1) double {mustBeInteger,mustBeNonnegative}
    options.MaximumLag (1,1) double {mustBeInteger,mustBeNonnegative} = 4
end

maximumLag = options.MaximumLag;
if lag > maximumLag
    error("macro:v2:buildCommonSampleLagDesign:LagExceedsMaximum", ...
        "Lag %d exceeds the common-sample maximum lag %d.",lag,maximumLag);
end

data = macro.validateQuarterlyData(data);
n = height(data);
responseRows = (maximumLag+1:n)';
numParameters = 4;
if numel(responseRows) <= numParameters
    error("macro:v2:buildCommonSampleLagDesign:InsufficientHistory", ...
        "The common-sample design requires more than %d observations " + ...
        "after reserving %d quarters of lag history; received %d rows.", ...
        numParameters,maximumLag,n);
end
predictorRows = responseRows-lag;

if istimetable(data)
    dates = data.Properties.RowTimes;
else
    dates = data.observation_date;
end

X = [ones(numel(responseRows),1), ...
    data.Inflation(predictorRows), ...
    data.Unemployment(predictorRows), ...
    data.InterestRate(predictorRows)];
Y = data.GDPGrowth(responseRows);

design = struct( ...
    "Lag",lag, ...
    "MaximumLag",maximumLag, ...
    "X",X, ...
    "Y",Y, ...
    "Dates",dates(responseRows), ...
    "ResponseRows",responseRows, ...
    "PredictorRows",predictorRows, ...
    "PredictorSourceRows",[nan(numel(responseRows),1), ...
        repmat(predictorRows,1,3)], ...
    "VariableNames",["Intercept","Inflation", ...
        "Unemployment","InterestRate"], ...
    "Observations",numel(responseRows), ...
    "Interpretation", ...
        "Descriptive/in-sample design on a common response sample");
end
