function result = clarkWestTest(largerModelForecasts,benchmarkForecasts,options)
%CLARKWESTTEST One-sided Clark-West test for a nested larger model.
%   Positive adjusted differentials favor the larger model.

arguments
    largerModelForecasts table
    benchmarkForecasts table
    options.Bandwidth (1,1) double {mustBeInteger} = -1
    options.SmallSampleThreshold (1,1) double ...
        {mustBeInteger,mustBePositive} = 30
end

pair = macro.v2.validateForecastPair( ...
    largerModelForecasts,benchmarkForecasts);
modelErrors = pair.Actual-pair.ModelForecast;
benchmarkErrors = pair.Actual-pair.BenchmarkForecast;
adjustment = (pair.BenchmarkForecast-pair.ModelForecast).^2;
differential = benchmarkErrors.^2-modelErrors.^2+adjustment;
inference = macro.v2.lossDifferentialInference(differential, ...
    Bandwidth=options.Bandwidth,Alternative="greater");
smallSample = pair.Observations < options.SmallSampleThreshold;
if smallSample
    warning("macro:v2:clarkWestTest:SmallSample", ...
        "Clark-West inference uses only %d forecasts; interpret non-rejection cautiously.", ...
        pair.Observations);
end

result = struct( ...
    "TestFamily","Clark-West", ...
    "Loss","squared", ...
    "Observations",pair.Observations, ...
    "ForecastStart",pair.Dates(1), ...
    "ForecastEnd",pair.Dates(end), ...
    "Horizon",1, ...
    "HACBandwidth",inference.Bandwidth, ...
    "MeanLossDifferential",inference.MeanDifferential, ...
    "DMStatistic",NaN, ...
    "HLNCorrectionFactor",NaN, ...
    "Statistic",inference.Statistic, ...
    "PValue",inference.PValue, ...
    "Status",inference.Status, ...
    "SmallSampleWarning",smallSample);
end
