function retrieval = fetchAlfredSeries(cfg,seriesID,options)
%FETCHALFREDSERIES Retrieve or reload one validated ALFRED vintage panel.
%   Network access is opt-in through Refresh=true. The FRED API key is read
%   only from the environment variable named by the V2 configuration.

arguments
    cfg (1,1) struct
    seriesID (1,1) string
    options.RealtimeStart (1,1) datetime = datetime(1776,7,4)
    options.RealtimeEnd (1,1) datetime = dateshift(datetime("today"), ...
        "start","day")
    options.Refresh (1,1) logical = false
    options.PageSize (1,1) double {mustBeInteger,mustBePositive} = 10000
    options.HttpClient (1,1) function_handle = @defaultHttpClient
end

allowedSeries = ["GDPC1","CPIAUCSL","UNRATE","FEDFUNDS"];
if ~ismember(seriesID,allowedSeries)
    error("macro:v2:fetchAlfredSeries:UnsupportedSeries", ...
        "Unsupported ALFRED series: %s",seriesID);
end
if isnat(options.RealtimeStart) || isnat(options.RealtimeEnd) || ...
        options.RealtimeStart > options.RealtimeEnd
    error("macro:v2:fetchAlfredSeries:InvalidRealtimeWindow", ...
        "RealtimeStart must not be later than RealtimeEnd.");
end
if options.PageSize > 100000
    error("macro:v2:fetchAlfredSeries:InvalidPageSize", ...
        "PageSize must not exceed the FRED API limit of 100000.");
end

requiredConfig = ["ProjectRoot","OutputRoot","VintageDataDir", ...
    "AlfredEndpoint","AlfredApiKeyEnvironmentVariable"];
missingConfig = requiredConfig(~isfield(cfg,requiredConfig));
if ~isempty(missingConfig)
    error("macro:v2:fetchAlfredSeries:InvalidConfiguration", ...
        "V2 configuration is missing field(s): %s", ...
        strjoin(missingConfig,", "));
end

macro.v2.ensureOutputDirectories(cfg);
[dataPath,metadataPath] = cachePaths( ...
    cfg,seriesID,options.RealtimeStart,options.RealtimeEnd);
environmentName = string(cfg.AlfredApiKeyEnvironmentVariable);

if ~options.Refresh
    retrieval = loadCache(dataPath,metadataPath,seriesID, ...
        options.RealtimeStart,options.RealtimeEnd, ...
        string(getenv(environmentName)));
    return;
end

apiKey = string(getenv(environmentName));
if strlength(apiKey) == 0
    error("macro:v2:fetchAlfredSeries:MissingApiKey", ...
        "ALFRED refresh requires the configured API-key environment variable.");
end
endpoint = validateCredentialFreeEndpoint(string(cfg.AlfredEndpoint));

[panel,missingObservationCount] = downloadPages( ...
    endpoint,seriesID,apiKey, ...
    options.RealtimeStart,options.RealtimeEnd,options.PageSize, ...
    options.HttpClient);
panel = macro.v2.validateVintagePanel(panel);
checksum = macro.v2.vintagePanelChecksum(panel);

metadata = struct( ...
    "schemaVersion","1.0", ...
    "seriesID",seriesID, ...
    "retrievedAtUTC",string(datetime("now","TimeZone","UTC", ...
        "Format","yyyy-MM-dd'T'HH:mm:ss.SSSXXX")), ...
    "realtimeStart",string(options.RealtimeStart,"yyyy-MM-dd"), ...
    "realtimeEnd",string(options.RealtimeEnd,"yyyy-MM-dd"), ...
    "sourceEndpoint",endpoint, ...
    "rowCount",height(panel), ...
    "missingObservationCount",missingObservationCount, ...
    "checksumAlgorithm","SHA-256", ...
    "checksumSHA256",checksum, ...
    "dataFile",string(java.io.File(char(dataPath)).getName()));
assertCredentialFreeMetadata(metadata,apiKey);

writeCache(panel,metadata,dataPath,metadataPath);
retrieval = struct( ...
    "Panel",panel, ...
    "Metadata",metadata, ...
    "Source","network", ...
    "DataPath",dataPath, ...
    "MetadataPath",metadataPath);
end

function [panel,missingCount] = downloadPages(endpoint,seriesID,apiKey, ...
        realtimeStart,realtimeEnd,pageSize,httpClient)
offset = 0;
expectedCount = NaN;
receivedCount = 0;
rawObservations = [];

while isnan(expectedCount) || receivedCount < expectedCount
    request = struct( ...
        "series_id",seriesID, ...
        "api_key",apiKey, ...
        "file_type","json", ...
        "realtime_start",string(realtimeStart,"yyyy-MM-dd"), ...
        "realtime_end",string(realtimeEnd,"yyyy-MM-dd"), ...
        "output_type",1, ...
        "sort_order","asc", ...
        "limit",pageSize, ...
        "offset",offset);
    try
        response = httpClient(endpoint,request);
    catch
        error("macro:v2:fetchAlfredSeries:HttpError", ...
            "ALFRED request failed for %s at offset %d.",seriesID,offset);
    end

    if isstruct(response) && isfield(response,"error_code")
        error("macro:v2:fetchAlfredSeries:ApiError", ...
            "ALFRED API returned an error for %s.",seriesID);
    end
    required = ["count","offset","limit","observations"];
    if ~isstruct(response) || any(~isfield(response,required))
        error("macro:v2:fetchAlfredSeries:MalformedResponse", ...
            "ALFRED response is missing required pagination fields.");
    end
    if ~isnumeric(response.count) || ~isscalar(response.count) || ...
            response.count < 0 || fix(response.count) ~= response.count || ...
            ~isnumeric(response.offset) || ~isscalar(response.offset) || ...
            response.offset ~= offset
        error("macro:v2:fetchAlfredSeries:MalformedResponse", ...
            "ALFRED response contains invalid count or offset values.");
    end
    if isnan(expectedCount)
        expectedCount = double(response.count);
    elseif double(response.count) ~= expectedCount
        error("macro:v2:fetchAlfredSeries:MalformedResponse", ...
            "ALFRED response count changed between pages.");
    end

    pageObservations = response.observations;
    if isempty(pageObservations)
        if expectedCount == 0
            break;
        end
        error("macro:v2:fetchAlfredSeries:MalformedResponse", ...
            "ALFRED pagination ended before the declared row count.");
    end
    if ~isstruct(pageObservations)
        error("macro:v2:fetchAlfredSeries:MalformedResponse", ...
            "ALFRED observations must be a structure array.");
    end
    if isempty(rawObservations)
        rawObservations = pageObservations(:);
    else
        try
            rawObservations = [rawObservations;pageObservations(:)]; %#ok<AGROW>
        catch
            error("macro:v2:fetchAlfredSeries:MalformedResponse", ...
                "ALFRED observation fields changed between pages.");
        end
    end
    pageCount = numel(pageObservations);
    receivedCount = receivedCount + pageCount;
    offset = offset + pageCount;
    if receivedCount > expectedCount
        error("macro:v2:fetchAlfredSeries:MalformedResponse", ...
            "ALFRED returned more rows than its declared count.");
    end
end

if expectedCount == 0
    error("macro:v2:fetchAlfredSeries:EmptySeries", ...
        "ALFRED returned no observations for %s.",seriesID);
end
[panel,missingCount] = observationsToPanel(rawObservations,seriesID);
if isempty(panel)
    error("macro:v2:fetchAlfredSeries:EmptySeries", ...
        "ALFRED returned no finite observations for %s.",seriesID);
end
end

function [panel,missingCount] = observationsToPanel(observations,seriesID)
required = ["date","realtime_start","realtime_end","value"];
if any(~isfield(observations,required))
    error("macro:v2:fetchAlfredSeries:MalformedObservation", ...
        "ALFRED observation records are missing required fields.");
end

numRows = numel(observations);
SeriesID = repmat(seriesID,numRows,1);
ObservationDate = NaT(numRows,1);
RealtimeStart = NaT(numRows,1);
RealtimeEnd = NaT(numRows,1);
Value = NaN(numRows,1);
keep = true(numRows,1);

for rowIndex = 1:numRows
    rawValue = string(observations(rowIndex).value);
    if rawValue == "." || ismissing(rawValue)
        keep(rowIndex) = false;
        continue;
    end
    try
        ObservationDate(rowIndex) = datetime( ...
            string(observations(rowIndex).date), ...
            "InputFormat","yyyy-MM-dd");
        RealtimeStart(rowIndex) = datetime( ...
            string(observations(rowIndex).realtime_start), ...
            "InputFormat","yyyy-MM-dd");
        RealtimeEnd(rowIndex) = datetime( ...
            string(observations(rowIndex).realtime_end), ...
            "InputFormat","yyyy-MM-dd");
    catch
        error("macro:v2:fetchAlfredSeries:MalformedObservation", ...
            "ALFRED observation contains an invalid date field.");
    end
    Value(rowIndex) = str2double(rawValue);
    if ~isfinite(Value(rowIndex))
        error("macro:v2:fetchAlfredSeries:MalformedObservation", ...
            "ALFRED observation contains a nonnumeric value.");
    end
end

missingCount = sum(~keep);
panel = table(SeriesID(keep),ObservationDate(keep),RealtimeStart(keep), ...
    RealtimeEnd(keep),Value(keep), ...
    'VariableNames',{'SeriesID','ObservationDate','RealtimeStart', ...
    'RealtimeEnd','Value'});
end

function response = defaultHttpClient(endpoint,request)
webOptions = weboptions("ContentType","json","Timeout",60);
try
    response = webread(endpoint, ...
        "series_id",request.series_id, ...
        "api_key",request.api_key, ...
        "file_type",request.file_type, ...
        "realtime_start",request.realtime_start, ...
        "realtime_end",request.realtime_end, ...
        "output_type",request.output_type, ...
        "sort_order",request.sort_order, ...
        "limit",request.limit, ...
        "offset",request.offset,webOptions);
catch
    % MATLAB's raw web-service exception can contain the complete query
    % URL. Never propagate it because that URL contains the credential.
    error("macro:v2:fetchAlfredSeries:RedactedTransportFailure", ...
        "ALFRED HTTP transport failed; credential-bearing details were redacted.");
end
end

function endpoint = validateCredentialFreeEndpoint(endpoint)
% Cache metadata and diagnostics must contain only a clean base endpoint.
if ~isscalar(endpoint) || strlength(endpoint) == 0 || ...
        contains(lower(endpoint),"api_key") || ...
        contains(endpoint,"?") || contains(endpoint,"#")
    error("macro:v2:fetchAlfredSeries:UnsafeEndpoint", ...
        "AlfredEndpoint must be a credential-free base URL without a query or fragment.");
end
end

function assertCredentialFreeMetadata(metadata,apiKey)
serialized = string(jsonencode(metadata));
containsCredential = strlength(apiKey) > 0 && contains(serialized,apiKey);
if containsCredential || contains(lower(serialized),"api_key")
    error("macro:v2:fetchAlfredSeries:CredentialLeakPrevented", ...
        "Credential-bearing retrieval metadata was blocked before persistence.");
end
end

function [dataPath,metadataPath] = cachePaths( ...
        cfg,seriesID,realtimeStart,realtimeEnd)
stem = seriesID + "_" + string(realtimeStart,"yyyyMMdd") + "_" + ...
    string(realtimeEnd,"yyyyMMdd");
dataPath = fullfile(string(cfg.VintageDataDir),stem+".csv");
metadataPath = fullfile(string(cfg.VintageDataDir),stem+".metadata.json");
end

function retrieval = loadCache(dataPath,metadataPath,seriesID, ...
        realtimeStart,realtimeEnd,apiKey)
if ~isfile(dataPath) && ~isfile(metadataPath)
    error("macro:v2:fetchAlfredSeries:CacheMiss", ...
        "No cached ALFRED snapshot exists; explicitly request a refresh.");
end
if ~isfile(dataPath) || ~isfile(metadataPath)
    error("macro:v2:fetchAlfredSeries:IncompleteCache", ...
        "Cached ALFRED data and metadata must both be present.");
end

panel = macro.v2.readVintagePanel(dataPath);
try
    metadata = jsondecode(fileread(metadataPath));
catch
    error("macro:v2:fetchAlfredSeries:MalformedCacheMetadata", ...
        "Cached ALFRED metadata is not valid JSON.");
end
required = ["schemaVersion","seriesID","retrievedAtUTC", ...
    "realtimeStart","realtimeEnd","sourceEndpoint","rowCount", ...
    "missingObservationCount","checksumAlgorithm","checksumSHA256", ...
    "dataFile"];
if ~isstruct(metadata) || any(~isfield(metadata,required))
    error("macro:v2:fetchAlfredSeries:MalformedCacheMetadata", ...
        "Cached ALFRED metadata is missing required fields.");
end
assertCredentialFreeMetadata(metadata,apiKey);
validateCredentialFreeEndpoint(string(metadata.sourceEndpoint));
if string(metadata.seriesID) ~= seriesID || ...
        string(metadata.realtimeStart) ~= string(realtimeStart,"yyyy-MM-dd") || ...
        string(metadata.realtimeEnd) ~= string(realtimeEnd,"yyyy-MM-dd") || ...
        double(metadata.rowCount) ~= height(panel) || ...
        string(metadata.checksumAlgorithm) ~= "SHA-256" || ...
        string(metadata.dataFile) ~= string(java.io.File(char(dataPath)).getName())
    error("macro:v2:fetchAlfredSeries:CacheMetadataMismatch", ...
        "Cached ALFRED metadata does not match the requested snapshot.");
end
checksum = macro.v2.vintagePanelChecksum(panel);
if string(metadata.checksumSHA256) ~= checksum
    error("macro:v2:fetchAlfredSeries:ChecksumMismatch", ...
        "Cached ALFRED data failed checksum validation.");
end

retrieval = struct( ...
    "Panel",panel, ...
    "Metadata",metadata, ...
    "Source","cache", ...
    "DataPath",dataPath, ...
    "MetadataPath",metadataPath);
end

function writeCache(panel,metadata,dataPath,metadataPath)
panel.ObservationDate.Format = "yyyy-MM-dd";
panel.RealtimeStart.Format = "yyyy-MM-dd";
panel.RealtimeEnd.Format = "yyyy-MM-dd";
writetable(panel,dataPath);

jsonText = jsonencode(metadata,"PrettyPrint",true);
fileID = fopen(metadataPath,"w","n","UTF-8");
if fileID < 0
    error("macro:v2:fetchAlfredSeries:CacheWriteFailed", ...
        "Could not create ALFRED cache metadata.");
end
cleanup = onCleanup(@() fclose(fileID));
count = fwrite(fileID,jsonText,"char");
if count ~= strlength(string(jsonText))
    error("macro:v2:fetchAlfredSeries:CacheWriteFailed", ...
        "Could not write complete ALFRED cache metadata.");
end
end
