function retrievals = fetchCurrentAlfredSeries(cfg,options)
%FETCHCURRENTALFREDSERIES Retrieve/reload all four current macro series.

arguments
    cfg (1,1) struct
    options.RealtimeStart (1,1) datetime = datetime(1776,7,4)
    options.RealtimeEnd (1,1) datetime = dateshift(datetime("today"), ...
        "start","day")
    options.Refresh (1,1) logical = false
    options.PageSize (1,1) double {mustBeInteger,mustBePositive} = 10000
    options.HttpClient = []
end

seriesIDs = ["GDPC1","CPIAUCSL","UNRATE","FEDFUNDS"];
retrievals = cell(numel(seriesIDs),1);
for seriesIndex = 1:numel(seriesIDs)
    if options.Refresh && isempty(options.HttpClient)
        retrievals{seriesIndex} = macro.v2.fetchAlfredSeries( ...
            cfg,seriesIDs(seriesIndex), ...
            RealtimeStart=options.RealtimeStart, ...
            RealtimeEnd=options.RealtimeEnd,Refresh=true, ...
            PageSize=options.PageSize);
    elseif options.Refresh
        if ~isa(options.HttpClient,"function_handle")
            error("macro:v2:fetchCurrentAlfredSeries:InvalidHttpClient", ...
                "HttpClient must be a function handle when supplied.");
        end
        retrievals{seriesIndex} = macro.v2.fetchAlfredSeries( ...
            cfg,seriesIDs(seriesIndex), ...
            RealtimeStart=options.RealtimeStart, ...
            RealtimeEnd=options.RealtimeEnd,Refresh=true, ...
            PageSize=options.PageSize,HttpClient=options.HttpClient);
    else
        retrievals{seriesIndex} = macro.v2.fetchAlfredSeries( ...
            cfg,seriesIDs(seriesIndex), ...
            RealtimeStart=options.RealtimeStart, ...
            RealtimeEnd=options.RealtimeEnd,Refresh=false, ...
            PageSize=options.PageSize);
    end
end
end
