function target = firstReleaseGDPGrowth(panel,targetQuarterStart,protocol)
%FIRSTRELEASEGDPGROWTH Build GDP growth from the first target-quarter vintage.
%   Both target- and prior-quarter GDP levels are selected from the
%   real-time snapshot valid on the target quarter's first release date.

arguments
    panel table
    targetQuarterStart (1,1) datetime
    protocol (1,1) struct = macro.v2.forecastProtocol()
end

panel = macro.v2.validateVintagePanel(panel);
if isnat(targetQuarterStart) || ...
        targetQuarterStart ~= dateshift(targetQuarterStart,"start","quarter")
    error("macro:v2:firstReleaseGDPGrowth:InvalidTargetQuarter", ...
        "TargetQuarterStart must be the first day of a calendar quarter.");
end

seriesID = string(protocol.TargetSeriesID);
targetRows = panel.SeriesID == seriesID & ...
    panel.ObservationDate == targetQuarterStart;
if ~any(targetRows)
    error("macro:v2:firstReleaseGDPGrowth:MissingTarget", ...
        "No target-quarter GDP vintage is available.");
end

firstReleaseDate = min(panel.RealtimeStart(targetRows));
targetSelection = macro.v2.asOfValue( ...
    panel,seriesID,targetQuarterStart,firstReleaseDate);
priorQuarterStart = targetQuarterStart - calmonths(3);
priorSelection = macro.v2.asOfValue( ...
    panel,seriesID,priorQuarterStart,firstReleaseDate);

growth = 400 * log(targetSelection.Value/priorSelection.Value);
target = struct( ...
    "Name",string(protocol.TargetName), ...
    "SeriesID",seriesID, ...
    "TargetQuarter",targetQuarterStart, ...
    "FirstReleaseDate",firstReleaseDate, ...
    "TargetGDP",targetSelection.Value, ...
    "PriorQuarterGDP",priorSelection.Value, ...
    "TargetVintageStart",targetSelection.RealtimeStart, ...
    "PriorVintageStart",priorSelection.RealtimeStart, ...
    "GDPGrowth",growth, ...
    "Definition",string(protocol.TargetDefinition));
end
