function protocol = forecastEvaluationProtocol()
%FORECASTEVALUATIONPROTOCOL Predeclared V2.5 evaluation specifications.

TestFamily = [repmat("DM-HLN",4,1);repmat("Clark-West",2,1)];
Model = ["Nested selected";"Nested selected";"Nested selected"; ...
    "V1 fixed historical OLS";"V1 fixed historical OLS"; ...
    "V1 expanding OLS"];
Benchmark = ["Persistence";"V1 fixed historical OLS"; ...
    "V1 expanding OLS";"V1 expanding OLS"; ...
    "Persistence";"Persistence"];
Loss = repmat("Squared error",6,1);
Alternative = [repmat("Model has lower expected forecast loss",4,1); ...
    repmat("Larger model has a positive Clark-West adjusted differential",2,1)];
Comparisons = table(TestFamily,Model,Benchmark,Loss,Alternative);

Window = ["Full finalized outer sample";"Pre-COVID 2016-2019"; ...
    "COVID 2020";"Post-COVID 2021+"];
StartQuarter = [NaT;datetime(2016,1,1);datetime(2020,1,1); ...
    datetime(2021,1,1)];
EndQuarter = [NaT;datetime(2019,10,1);datetime(2020,10,1);NaT];
MinimumObservations = [8;8;4;8];
RequireCompleteDeclaredWindow = [false;true;true;false];
Windows = table(Window,StartQuarter,EndQuarter,MinimumObservations, ...
    RequireCompleteDeclaredWindow);

protocol = struct( ...
    "Alpha",0.05, ...
    "ForecastHorizon",1, ...
    "PrimaryDMLoss","Squared error", ...
    "HACBandwidthRule","min(n-1,floor(4*(n/100)^(2/9)))", ...
    "HACKernel","Bartlett", ...
    "HLNSmallSampleCorrection",true, ...
    "SmallSampleWarningThreshold",30, ...
    "MASEScaleDefinition", ...
        "At each forecast origin: mean absolute first difference of " + ...
        "first-release GDP growth using training targets only", ...
    "HuberDelta",1.345, ...
    "HuberDefinition", ...
        "Mean Huber loss of forecast errors divided by the origin-specific " + ...
        "training-only MASE scale", ...
    "BootstrapMethod","Fixed-seed circular moving-block bootstrap", ...
    "BootstrapReplications",2000, ...
    "BootstrapBlockLength",4, ...
    "BootstrapSeed",2505, ...
    "BootstrapConfidenceLevel",0.95, ...
    "MultipleTestingAdjustment","Holm family-wise adjustment across all " + ...
        "predeclared formal comparisons", ...
    "Comparisons",Comparisons, ...
    "Windows",Windows);
end
