function protocol = forecastProtocol()
%FORECASTPROTOCOL Central definition of the initial V2 forecast exercise.
%   V2 targets the first published vintage of quarterly real GDP growth.
%   The primary origin is the 45th calendar day of the target quarter. The
%   strict origin is the calendar day immediately before the quarter starts.

ruleName = ["primary-early-quarter";"strict-quarter-start"];
offsetDays = [44;-1];
description = [ ...
    "45th calendar day of the target quarter (quarter start + 44 days)"; ...
    "Calendar day immediately before the target quarter starts"];

protocol = struct( ...
    "TargetSeriesID","GDPC1", ...
    "TargetName","FirstReleaseAnnualizedQuarterlyRealGDPGrowth", ...
    "TargetDefinition", ...
        "400 times the log difference between target-quarter and " + ...
        "prior-quarter GDPC1 values in the target quarter's first " + ...
        "published vintage", ...
    "EvaluationStart",datetime(2016,1,1), ...
    "EvaluationEndRule","Latest evaluable target quarter in the cache", ...
    "IncompleteInformationRule", ...
        "Mark incomplete and retain missing feature values; do not " + ...
        "impute or aggregate partial quarters", ...
    "PrimaryOriginRule","primary-early-quarter", ...
    "StrictOriginRule","strict-quarter-start", ...
    "OriginRules",table(ruleName,offsetDays,description, ...
        'VariableNames',{'Name','OffsetDays','Description'}));
end
