function protocol = inferenceProtocol()
%INFERENCEPROTOCOL Central V2.2 stationarity and HAC specifications.

Variable = ["RealGDP";"GDPGrowth";"CPI";"Inflation"; ...
    "Unemployment";"DeltaUnemployment"; ...
    "InterestRate";"DeltaInterestRate"];
SourceVariable = ["RealGDP";"GDPGrowth";"CPI";"Inflation"; ...
    "Unemployment";"Unemployment";"InterestRate";"InterestRate"];
Transformation = ["Level";"V1 annualized log growth";"Level"; ...
    "V1 annualized log growth";"Level";"First difference candidate"; ...
    "Level";"First difference candidate"];
ADFModel = ["TS";"ARD";"TS";"ARD";"ARD";"ARD";"ARD";"ARD"];
KPSSTrend = [true;false;true;false;false;false;false;false];
Role = ["Raw level";"V1 transformation";"Raw level"; ...
    "V1 transformation";"Baseline level";"Candidate only"; ...
    "Baseline level";"Candidate only"];

protocol = struct( ...
    "Alpha",0.05, ...
    "ADFMaximumLagCap",8, ...
    "ADFLagBoundRule", ...
        "min(8,floor(12*(n/100)^(1/4)),floor((n-5)/2))", ...
    "ADFLagSelectionCriterion","AIC on a common pmax-trimmed sample", ...
    "BandwidthRule","min(n-1,floor(4*(n/100)^(2/9)))", ...
    "HACKernel","Bartlett", ...
    "HACSmallSampleCorrection",false, ...
    "Specifications",table(Variable,SourceVariable,Transformation, ...
        ADFModel,KPSSTrend,Role));
end
