function protocol = lagComparisonProtocol()
%LAGCOMPARISONPROTOCOL Predeclare the V2.3 equal-sample comparison.
%   The comparison is descriptive and in-sample. It does not select the
%   forecasting model used by V1 or any future V2 forecasting analysis.

candidateLags = (0:4)';
protocol = struct( ...
    "CandidateLags",candidateLags, ...
    "MaximumLag",max(candidateLags), ...
    "V1SelectedLag",1, ...
    "CommonSampleRule", ...
        "Response rows begin after the maximum candidate lag", ...
    "Interpretation", ...
        "Descriptive/in-sample criteria; not forecast evidence");
end
