function protocol = modelSelectionProtocol()
%MODELSELECTIONPROTOCOL Central deterministic V2.4 selection rules.

ridgeGrid = [0.1;1;10];
Candidate = [ ...
    "Persistence";"Historical mean";"AR(1)";"AR(2)";"AR(3)"; ...
    "AR(4)";"V1-style macro OLS";"HAC-inference macro OLS"; ...
    "Ridge macro (lambda=0.1)";"Ridge macro (lambda=1)"; ...
    "Ridge macro (lambda=10)"];
ModelFamily = [ ...
    "Persistence";"HistoricalMean";repmat("AR",4,1); ...
    "MacroOLSClassical";"MacroOLSHAC";repmat("RidgeMacro",3,1)];
ARLag = [NaN;NaN;(1:4)';NaN;NaN;NaN(3,1)];
RidgeLambda = [NaN(8,1);ridgeGrid];
Priority = (1:numel(Candidate))';
Candidates = table(Candidate,ModelFamily,ARLag,RidgeLambda,Priority);

protocol = struct( ...
    "OriginRule","primary-early-quarter", ...
    "OuterEvaluationStart",datetime(2016,1,1), ...
    "InnerValidationMethod","expanding-window", ...
    "InnerValidationQuarters",12, ...
    "MinimumTrainingObservations",40, ...
    "MaximumARLag",4, ...
    "RidgePenaltyGrid",ridgeGrid, ...
    "RidgeStandardization", ...
        "Training-fold mean and sample standard deviation; intercept unpenalized", ...
    "SelectionCriterion","Inner expanding-window RMSE", ...
    "TieTolerance",1e-12, ...
    "TieBreakRule", ...
        "Lowest predeclared candidate priority, then lowest ridge penalty", ...
    "Candidates",Candidates);
end
