function prepared = prepareNestedModelingData(modelingDataset,informationSet,protocol)
%PREPARENESTEDMODELINGDATA Validate and align the V2.4 forecast dataset.

arguments
    modelingDataset table
    informationSet table
    protocol (1,1) struct = macro.v2.modelSelectionProtocol()
end

requiredModeling = ["TargetQuarter","OriginRule","ForecastOrigin", ...
    "InformationSetComplete","GDPGrowth_L1","Inflation_L1", ...
    "Unemployment_L1","InterestRate_L1", ...
    "TargetGDPGrowthFirstRelease","TargetFirstReleaseDate"];
macro.requireTableVariables(modelingDataset,requiredModeling, ...
    DataName="V2 real-time modeling dataset");
requiredInformation = ["TargetQuarter","OriginRule","ForecastOrigin", ...
    "Feature","Value","IsComplete","LatestSelectedVintageStart"];
macro.requireTableVariables(informationSet,requiredInformation, ...
    DataName="V2 forecast-origin information set");

modelingDataset.OriginRule = string(modelingDataset.OriginRule);
informationSet.OriginRule = string(informationSet.OriginRule);
modelingDataset = modelingDataset( ...
    modelingDataset.OriginRule == protocol.OriginRule,:);
informationSet = informationSet( ...
    informationSet.OriginRule == protocol.OriginRule,:);
if isempty(modelingDataset)
    error("macro:v2:prepareNestedModelingData:MissingOriginRule", ...
        "No rows use the required origin rule %s.",protocol.OriginRule);
end
if any(~modelingDataset.InformationSetComplete)
    incompleteDates = modelingDataset.TargetQuarter( ...
        ~modelingDataset.InformationSetComplete);
    error("macro:v2:prepareNestedModelingData:IncompleteInformationSet", ...
        "Nested selection does not impute incomplete information sets. " + ...
        "The first incomplete target is %s.",string(incompleteDates(1)));
end

modelingDataset = sortrows(modelingDataset,"TargetQuarter");
if height(unique(modelingDataset(:,"TargetQuarter"))) ~= ...
        height(modelingDataset)
    error("macro:v2:prepareNestedModelingData:DuplicateTarget", ...
        "Target quarters must be unique within the selected origin rule.");
end
if any(modelingDataset.TargetQuarter ~= ...
        dateshift(modelingDataset.TargetQuarter,"start","quarter")) || ...
        any(modelingDataset.TargetQuarter(2:end) ~= dateshift( ...
        modelingDataset.TargetQuarter(1:end-1),"start","quarter","next"))
    error("macro:v2:prepareNestedModelingData:QuarterlyGap", ...
        "Complete modeling rows must be consecutive quarter starts.");
end
if any(modelingDataset.ForecastOrigin >= ...
        modelingDataset.TargetFirstReleaseDate)
    error("macro:v2:prepareNestedModelingData:TargetKnownAtOrigin", ...
        "A first-release GDP target is already known at its forecast origin.");
end

numericVariables = ["GDPGrowth_L1","Inflation_L1", ...
    "Unemployment_L1","InterestRate_L1", ...
    "TargetGDPGrowthFirstRelease"];
for variable = numericVariables
    values = modelingDataset.(variable);
    if ~isnumeric(values) || any(~isfinite(values))
        error("macro:v2:prepareNestedModelingData:InvalidNumericData", ...
            "%s must be finite numeric data.",variable);
    end
end

featureAvailability = NaT(height(modelingDataset),1);
expectedFeatures = ["GDPGrowth_L1","Inflation_L1", ...
    "Unemployment_L1","InterestRate_L1"];
for row = 1:height(modelingDataset)
    matches = informationSet.TargetQuarter == ...
        modelingDataset.TargetQuarter(row) & ...
        informationSet.ForecastOrigin == modelingDataset.ForecastOrigin(row);
    rows = informationSet(matches,:);
    if height(rows) ~= numel(expectedFeatures) || ...
            ~all(ismember(expectedFeatures,string(rows.Feature))) || ...
            ~all(rows.IsComplete) || any(~isfinite(rows.Value)) || ...
            any(isnat(rows.LatestSelectedVintageStart))
        error("macro:v2:prepareNestedModelingData:InvalidProvenance", ...
            "Target %s lacks four complete, finite feature provenance rows.", ...
            string(modelingDataset.TargetQuarter(row)));
    end
    macro.v2.validateAvailability(table( ...
        rows.LatestSelectedVintageStart,rows.ForecastOrigin, ...
        VariableNames={'AvailableDate','ForecastOrigin'}));
    featureAvailability(row) = max(rows.LatestSelectedVintageStart);
end

n = height(modelingDataset);
maximumLag = protocol.MaximumARLag;
if n-maximumLag < protocol.MinimumTrainingObservations+ ...
        protocol.InnerValidationQuarters+1
    error("macro:v2:prepareNestedModelingData:InsufficientHistory", ...
        "Nested validation requires at least %d consecutive complete rows; " + ...
        "received %d.",maximumLag+protocol.MinimumTrainingObservations+ ...
        protocol.InnerValidationQuarters+1,n);
end

sourceRows = (maximumLag+1:n)';
numRows = numel(sourceRows);
gdpLags = zeros(numRows,maximumLag);
inflationLags = zeros(numRows,maximumLag);
unemploymentLags = zeros(numRows,maximumLag);
rateLags = zeros(numRows,maximumLag);
predictorSourceRows = zeros(numRows,1+3*maximumLag);
for designRow = 1:numRows
    source = sourceRows(designRow);
    lagRows = source-(0:maximumLag-1);
    gdpLags(designRow,:) = modelingDataset.GDPGrowth_L1(lagRows)';
    inflationLags(designRow,:) = modelingDataset.Inflation_L1(lagRows)';
    unemploymentLags(designRow,:) = ...
        modelingDataset.Unemployment_L1(lagRows)';
    rateLags(designRow,:) = modelingDataset.InterestRate_L1(lagRows)';
    predictorSourceRows(designRow,:) = [source,lagRows,lagRows,lagRows];
end
macroX = [ones(numRows,1),gdpLags(:,1),inflationLags, ...
    unemploymentLags,rateLags];
macroNames = ["Intercept","GDPGrowth_L1", ...
    "Inflation_L1","Inflation_L2","Inflation_L3","Inflation_L4", ...
    "Unemployment_L1","Unemployment_L2","Unemployment_L3", ...
    "Unemployment_L4","InterestRate_L1","InterestRate_L2", ...
    "InterestRate_L3","InterestRate_L4"];
maxPredictorAvailability = NaT(numRows,1);
for designRow = 1:numRows
    maxPredictorAvailability(designRow) = max(featureAvailability( ...
        unique(predictorSourceRows(designRow,:))));
end
selected = modelingDataset(sourceRows,:);
if any(maxPredictorAvailability > selected.ForecastOrigin)
    error("macro:v2:prepareNestedModelingData:FutureVintage", ...
        "At least one constructed predictor was unavailable at its origin.");
end

prepared = struct( ...
    "Data",selected, ...
    "Y",selected.TargetGDPGrowthFirstRelease, ...
    "Persistence",gdpLags(:,1), ...
    "ARLags",gdpLags, ...
    "MacroX",macroX, ...
    "MacroVariableNames",macroNames, ...
    "OriginalRows",sourceRows, ...
    "PredictorSourceRows",predictorSourceRows, ...
    "MaximumPredictorAvailabilityDate",maxPredictorAvailability, ...
    "Protocol",protocol);
end
