function cfg = projectConfig(projectRoot,options)
%PROJECTCONFIG Build isolated paths and methodology settings for V2.
%   V2 output paths are deliberately separate from the V1 data, results,
%   figures, and repository root. OUTPUTROOT identifies the V2 root itself.

arguments
    projectRoot (1,1) string = ""
    options.OutputRoot (1,1) string = ""
    options.RefreshVintages (1,1) logical = false
    options.GenerateFigures (1,1) logical = true
    options.StopOnError (1,1) logical = true
end

if strlength(projectRoot) == 0
    projectRoot = macro.findProjectRoot( ...
        string(mfilename("fullpath"))+".m");
else
    projectRoot = macro.findProjectRoot(projectRoot);
end

if strlength(options.OutputRoot) == 0
    outputRoot = canonicalPath(fullfile(projectRoot,"v2_outputs"));
else
    outputRoot = canonicalPath(options.OutputRoot);
end

v1DataDir = canonicalPath(fullfile(projectRoot,"data"));
v1ResultsDir = canonicalPath(fullfile(projectRoot,"results"));
v1FiguresDir = canonicalPath(fullfile(projectRoot,"figures"));
protectedPaths = [ ...
    v1DataDir;v1ResultsDir;v1FiguresDir; ...
    canonicalPath(fullfile(projectRoot,"scripts")); ...
    canonicalPath(fullfile(projectRoot,"src")); ...
    canonicalPath(fullfile(projectRoot,"tests"))];

if pathsEqual(outputRoot,projectRoot) || isDescendant(projectRoot,outputRoot)
    error("macro:v2:projectConfig:V1OutputOverlap", ...
        "V2 OutputRoot must not be the repository root or its ancestor.");
end

for pathIndex = 1:numel(protectedPaths)
    if pathsOverlap(outputRoot,protectedPaths(pathIndex))
        error("macro:v2:projectConfig:V1OutputOverlap", ...
            "V2 OutputRoot must not overlap protected V1 path: %s", ...
            protectedPaths(pathIndex));
    end
end

protocol = macro.v2.forecastProtocol();
inferenceProtocol = macro.v2.inferenceProtocol();
lagComparisonProtocol = macro.v2.lagComparisonProtocol();
modelSelectionProtocol = macro.v2.modelSelectionProtocol();
forecastEvaluationProtocol = macro.v2.forecastEvaluationProtocol();
structuralStabilityProtocol = macro.v2.structuralStabilityProtocol();
cfg = struct( ...
    "ProjectRoot",projectRoot, ...
    "SourceDir",fullfile(projectRoot,"src"), ...
    "TestsDir",fullfile(projectRoot,"tests"), ...
    "V2TestsDir",fullfile(projectRoot,"tests","v2"), ...
    "FixtureDir",fullfile(projectRoot,"tests","fixtures","v2"), ...
    "V1BaselineManifest",fullfile(projectRoot,"config", ...
        "v1_baseline_manifest.json"), ...
    "V1DataDir",v1DataDir, ...
    "V1ResultsDir",v1ResultsDir, ...
    "V1FiguresDir",v1FiguresDir, ...
    "AlfredEndpoint", ...
        "https://api.stlouisfed.org/fred/series/observations", ...
    "AlfredApiKeyEnvironmentVariable","FRED_API_KEY", ...
    "OutputRoot",outputRoot, ...
    "DataDir",fullfile(outputRoot,"data"), ...
    "VintageDataDir",fullfile(outputRoot,"data","vintages"), ...
    "ResultsDir",fullfile(outputRoot,"results"), ...
    "FiguresDir",fullfile(outputRoot,"figures"), ...
    "RefreshVintages",options.RefreshVintages, ...
    "GenerateFigures",options.GenerateFigures, ...
    "StopOnError",options.StopOnError, ...
    "ForecastProtocol",protocol, ...
    "InferenceProtocol",inferenceProtocol, ...
    "LagComparisonProtocol",lagComparisonProtocol, ...
    "ModelSelectionProtocol",modelSelectionProtocol, ...
    "ForecastEvaluationProtocol",forecastEvaluationProtocol, ...
    "StructuralStabilityProtocol",structuralStabilityProtocol, ...
    "PrimaryForecastOriginRule",protocol.PrimaryOriginRule, ...
    "StrictForecastOriginRule",protocol.StrictOriginRule);
end

function tf = pathsOverlap(firstPath,secondPath)
firstPath = canonicalPath(firstPath);
secondPath = canonicalPath(secondPath);
tf = pathsEqual(firstPath,secondPath) || ...
    isDescendant(firstPath,secondPath) || ...
    isDescendant(secondPath,firstPath);
end

function tf = pathsEqual(firstPath,secondPath)
if ispc
    tf = strcmpi(firstPath,secondPath);
else
    tf = firstPath == secondPath;
end
end

function tf = isDescendant(candidate,parent)
candidate = canonicalPath(candidate);
parent = canonicalPath(parent) + string(filesep);
if ispc
    tf = startsWith(lower(candidate),lower(parent));
else
    tf = startsWith(candidate,parent);
end
end

function pathOut = canonicalPath(pathIn)
pathFile = java.io.File(char(pathIn));
if ~pathFile.isAbsolute()
    pathFile = java.io.File(char(pwd),char(pathIn));
end
pathOut = string(pathFile.getCanonicalPath());
end
