function assumptions = publicationDelayAssumptions(protocol)
%PUBLICATIONDELAYASSUMPTIONS Return the declared V2 timing assumptions.

arguments
    protocol (1,1) struct = macro.v2.forecastProtocol()
end

SeriesID = ["GDPC1";"CPIAUCSL";"UNRATE";"FEDFUNDS";"GDPC1"];
Role = ["Predictor";"Predictor";"Predictor";"Predictor";"Target"];
NativeFrequency = ["Quarterly";"Monthly";"Monthly";"Monthly";"Quarterly"];
ConstructedVariable = ["GDPGrowth_L1";"Inflation_L1"; ...
    "Unemployment_L1";"InterestRate_L1";string(protocol.TargetName)];
RequiredObservations = [2;6;3;3;2];
Aggregation = [ ...
    "400*log(prior quarter / two quarters back)"; ...
    "400*log(mean prior quarter / mean two quarters back)"; ...
    "Arithmetic mean of all three prior-quarter months"; ...
    "Arithmetic mean of all three prior-quarter months"; ...
    "400*log(target / prior quarter) at target first release"];
AvailabilityRule = [ ...
    "Every selected vintage must have RealtimeStart <= ForecastOrigin"; ...
    "All six monthly releases must be available by ForecastOrigin"; ...
    "All three monthly releases must be available by ForecastOrigin"; ...
    "All three monthly releases must be available by ForecastOrigin"; ...
    "Use the first target-quarter publication and its contemporaneous prior-quarter vintage"];
RaggedEdgeRule = repmat(string(protocol.IncompleteInformationRule),5,1);

assumptions = table(SeriesID,Role,NativeFrequency,ConstructedVariable, ...
    RequiredObservations,Aggregation,AvailabilityRule,RaggedEdgeRule);
end
