function reconstruction = reconstructQuarterlyInformationSet( ...
        panel,targetQuarterStart,originRule,protocol)
%RECONSTRUCTQUARTERLYINFORMATIONSET Build one vintage-aware V2 information set.
%   The initial foundation reconstructs the V1-style one-quarter-lag
%   features for the current four macro series. It intentionally does not
%   estimate or forecast a model.

arguments
    panel table
    targetQuarterStart (1,1) datetime
    originRule (1,1) string = "primary-early-quarter"
    protocol (1,1) struct = macro.v2.forecastProtocol()
end

panel = macro.v2.validateVintagePanel(panel);
origin = macro.v2.forecastOrigin( ...
    targetQuarterStart,originRule,protocol);
priorQuarterStart = targetQuarterStart - calmonths(3);
twoQuartersBackStart = targetQuarterStart - calmonths(6);

try
    gdpSelections = selectMany(panel,"GDPC1", ...
        [twoQuartersBackStart;priorQuarterStart],origin);
    unemploymentSelections = selectMany(panel,"UNRATE", ...
        monthlyDates(priorQuarterStart),origin);
    rateSelections = selectMany(panel,"FEDFUNDS", ...
        monthlyDates(priorQuarterStart),origin);
    cpiSelections = selectMany(panel,"CPIAUCSL", ...
        [monthlyDates(twoQuartersBackStart); ...
         monthlyDates(priorQuarterStart)],origin);
catch availabilityError
    if availabilityError.identifier == "macro:v2:asOfValue:ObservationUnavailable"
        wrapped = MException( ...
            "macro:v2:reconstructQuarterlyInformationSet:IncompleteInformationSet", ...
            "The requested origin does not contain every required observation.");
        wrapped = addCause(wrapped,availabilityError);
        throwAsCaller(wrapped);
    end
    rethrow(availabilityError);
end

gdpGrowth = 400 * log( ...
    gdpSelections.Value(2)/gdpSelections.Value(1));
cpiEarlier = mean(cpiSelections.Value(1:3));
cpiPrior = mean(cpiSelections.Value(4:6));
inflation = 400 * log(cpiPrior/cpiEarlier);
unemployment = mean(unemploymentSelections.Value);
interestRate = mean(rateSelections.Value);

Feature = ["GDPGrowth_L1";"Inflation_L1"; ...
    "Unemployment_L1";"InterestRate_L1"];
Value = [gdpGrowth;inflation;unemployment;interestRate];
AvailableDate = [ ...
    max(gdpSelections.AvailableDate); ...
    max(cpiSelections.AvailableDate); ...
    max(unemploymentSelections.AvailableDate); ...
    max(rateSelections.AvailableDate)];
ForecastOrigin = repmat(origin,4,1);
OriginRule = repmat(originRule,4,1);
TargetQuarter = repmat(targetQuarterStart,4,1);
SourceSeries = ["GDPC1";"CPIAUCSL";"UNRATE";"FEDFUNDS"];
SourceObservationDates = [ ...
    joinDates(gdpSelections.ObservationDate); ...
    joinDates(cpiSelections.ObservationDate); ...
    joinDates(unemploymentSelections.ObservationDate); ...
    joinDates(rateSelections.ObservationDate)];
SourceRealtimeStarts = [ ...
    joinDates(gdpSelections.RealtimeStart); ...
    joinDates(cpiSelections.RealtimeStart); ...
    joinDates(unemploymentSelections.RealtimeStart); ...
    joinDates(rateSelections.RealtimeStart)];

informationSet = table(Feature,Value,AvailableDate,ForecastOrigin, ...
    OriginRule,TargetQuarter,SourceSeries,SourceObservationDates, ...
    SourceRealtimeStarts);
informationSet = macro.v2.validateAvailability(informationSet);

reconstruction = struct( ...
    "ForecastOrigin",origin, ...
    "OriginRule",originRule, ...
    "TargetQuarter",targetQuarterStart, ...
    "InformationSet",informationSet, ...
    "Target",macro.v2.firstReleaseGDPGrowth( ...
        panel,targetQuarterStart,protocol));
end

function dates = monthlyDates(quarterStart)
dates = quarterStart + calmonths((0:2)');
end

function selections = selectMany(panel,seriesID,observationDates,origin)
selections = panel([],:);
selections.AvailableDate = datetime.empty(0,1);
selections.ForecastOrigin = datetime.empty(0,1);
for dateIndex = 1:numel(observationDates)
    selected = macro.v2.asOfValue( ...
        panel,seriesID,observationDates(dateIndex),origin);
    selections = [selections;selected]; %#ok<AGROW>
end
end

function value = joinDates(dates)
value = join(string(dates,"yyyy-MM-dd"),"|");
end
