function output = runStructuralStabilityAnalysis(cfg)
%RUNSTRUCTURALSTABILITYANALYSIS Run V2.6 ex-post stability diagnostics.
%   The V1 fixed-2020-Q1 result is reproduced as a named read-only
%   baseline. Unknown-break results are diagnostic and never enter V2.4 or
%   V2.5 forecast construction, selection, or evaluation.

if nargin < 1 || isempty(cfg)
    cfg = macro.v2.projectConfig();
end
if ~isfield(cfg,"StructuralStabilityProtocol")
    error("macro:v2:runStructuralStabilityAnalysis:InvalidConfiguration", ...
        "V2 configuration must contain StructuralStabilityProtocol.");
end
macro.v2.ensureOutputDirectories(cfg);
protocol = cfg.StructuralStabilityProtocol;
if ~protocol.ForecastUseProhibited
    error("macro:v2:runStructuralStabilityAnalysis:ForecastLeakageGuard", ...
        "Structural break diagnostics must be prohibited from forecast use.");
end

dataPath = fullfile(cfg.V1DataDir,"Macroeconomic_Data_Quarterly.csv");
baselinePath = fullfile(cfg.V1ResultsDir,"Structural_Break_Test.csv");
if ~isfile(dataPath) || ~isfile(baselinePath)
    error("macro:v2:runStructuralStabilityAnalysis:MissingV1Baseline", ...
        "Read-only V1 quarterly data and structural-break output are required.");
end
data = macro.validateQuarterlyData(readtable(dataPath,TextType="string"));
design = macro.buildForecastDesign(data);
X = design.X; Y = design.Y; dates = design.Dates;

fixed = macro.v2.chowBreakTest(X,Y,dates,protocol.V1BaselineBreakDate);
v1 = readtable(baselinePath,TextType="string");
if height(v1)~=1 || abs(fixed.Statistic-v1.ChowFStatistic)>1e-10 || ...
        v1.BreakDate~=protocol.V1BaselineBreakDate
    error("macro:v2:runStructuralStabilityAnalysis:V1ParityFailure", ...
        "The reproduced fixed-2020-Q1 statistic does not match V1.");
end

recursive = macro.v2.recursiveStabilityDiagnostics( ...
    X,Y,dates,design.VariableNames, ...
    CoefficientMinimumObservations= ...
        protocol.RecursiveCoefficientMinimumObservations, ...
    CUSUMAlpha=protocol.CUSUMAlpha, ...
    CUSUMBoundaryConstant=protocol.CUSUMBoundaryConstant, ...
    CUSUMSQAlpha=protocol.CUSUMSQAlpha, ...
    CUSUMSQReplications=protocol.CUSUMSQSimulationReplications, ...
    CUSUMSQSeed=protocol.CUSUMSQSimulationSeed);

search = macro.v2.supWaldBreakSearch(X,Y,dates, ...
    TrimFraction=protocol.CandidateTrimFraction, ...
    MinimumExtraObservations=protocol.MinimumExtraRegimeObservations, ...
    BootstrapReplications=protocol.BreakBootstrapReplications, ...
    BootstrapBlockLength=protocol.BreakBootstrapBlockLength, ...
    BootstrapSeed=protocol.BreakBootstrapSeed, ...
    ConfidenceLevel=protocol.BreakConfidenceLevel);

acuteCOVID = dates>=protocol.AcuteCOVIDStart & dates<=protocol.AcuteCOVIDEnd;
sensitivity = macro.v2.chowBreakTest(X(~acuteCOVID,:),Y(~acuteCOVID), ...
    dates(~acuteCOVID),protocol.V1BaselineBreakDate);

tests = stabilityTestTable(fixed,sensitivity,search,recursive,protocol, ...
    numel(Y),sum(acuteCOVID));
candidateBreaks = search.CandidateTable;
candidateBreaks.SupWaldGlobalBootstrapPValue = repmat( ...
    search.BootstrapGlobalPValue,height(candidateBreaks),1);
candidateBreaks.BreakDateUncertaintyStart = repmat( ...
    search.BreakDateUncertaintyStart,height(candidateBreaks),1);
candidateBreaks.BreakDateUncertaintyEnd = repmat( ...
    search.BreakDateUncertaintyEnd,height(candidateBreaks),1);
candidateBreaks.TrimFraction = repmat(search.TrimFraction, ...
    height(candidateBreaks),1);
candidateBreaks.MinimumRegimeObservations = repmat( ...
    search.MinimumRegimeObservations,height(candidateBreaks),1);
candidateBreaks.BootstrapBlockLength = repmat( ...
    search.BootstrapBlockLength,height(candidateBreaks),1);

regimeSummary = buildRegimeSummary(fixed,sensitivity,search,X,Y,protocol);
coefficientPaths = recursive.CoefficientPaths;
residualDiagnostics = recursive.ResidualDiagnostics;

resultPaths = [ ...
    fullfile(cfg.ResultsDir,"Structural_Stability_Tests.csv"); ...
    fullfile(cfg.ResultsDir,"Candidate_Break_Dates.csv"); ...
    fullfile(cfg.ResultsDir,"Recursive_Coefficient_Paths.csv"); ...
    fullfile(cfg.ResultsDir,"Regime_Summary_V2.csv"); ...
    fullfile(cfg.ResultsDir,"Recursive_Residual_Diagnostics.csv")];
writetable(tests,resultPaths(1));
writetable(candidateBreaks,resultPaths(2));
writetable(coefficientPaths,resultPaths(3));
writetable(regimeSummary,resultPaths(4));
writetable(residualDiagnostics,resultPaths(5));

figureFiles = strings(0,1);
if cfg.GenerateFigures
    figureFiles = createFigures(cfg,design,recursive,search);
end

output = struct( ...
    "Protocol",protocol,"Design",design,"V1Baseline",v1, ...
    "Fixed2020Test",fixed,"COVIDSensitivityTest",sensitivity, ...
    "RecursiveDiagnostics",recursive,"SupWaldSearch",search, ...
    "StructuralStabilityTests",tests,"CandidateBreakDates",candidateBreaks, ...
    "RecursiveCoefficientPaths",coefficientPaths, ...
    "RecursiveResidualDiagnostics",residualDiagnostics, ...
    "RegimeSummary",regimeSummary,"ResultFiles",resultPaths, ...
    "FigureFiles",figureFiles,"ForecastInputsChanged",false, ...
    "MultipleBreakAnalysisImplemented",false);
end

function tests = stabilityTestTable(fixed,sensitivity,search,recursive,protocol,n,excluded)
Test = ["V1 fixed 2020 Q1 Chow baseline"; ...
    "V2 reproduced fixed 2020 Q1 Chow"; ...
    "Fixed 2020 Q1 excluding acute COVID quarters"; ...
    "Trimmed sup-Wald single-break search";"CUSUM";"CUSUMSQ"];
Scope = ["V1 read-only baseline";repmat(protocol.AnalysisScope,5,1)];
Statistic = [fixed.Statistic;fixed.Statistic;sensitivity.Statistic; ...
    search.SupStatistic;recursive.CUSUMMaxBoundaryRatio; ...
    recursive.CUSUMSQMaxDeviation];
ReferenceThreshold = [NaN;NaN;NaN;NaN;1; ...
    recursive.CUSUMSQCriticalDeviation];
PointwisePValue = [fixed.PValue;fixed.PValue;sensitivity.PValue; ...
    search.NaivePointwisePValue;NaN;NaN];
GlobalOrBootstrapPValue = [NaN;NaN;NaN;search.BootstrapGlobalPValue;NaN;NaN];
RejectAt5Percent = [fixed.PValue<.05;fixed.PValue<.05; ...
    sensitivity.PValue<.05;search.BootstrapGlobalPValue<.05; ...
    recursive.CUSUMReject;recursive.CUSUMSQReject];
SampleSize = [n;n;n-excluded;n;n;n];
BreakDate = [protocol.V1BaselineBreakDate;protocol.V1BaselineBreakDate; ...
    protocol.V1BaselineBreakDate;search.BreakDate;NaT;NaT];
UncertaintyStart = [NaT;NaT;NaT;search.BreakDateUncertaintyStart;NaT;NaT];
UncertaintyEnd = [NaT;NaT;NaT;search.BreakDateUncertaintyEnd;NaT;NaT];
ExPostOnly = [false;true;true;true;true;true];
Caveat = [ ...
    "Committed V1 fixed-date Chow-style calculation"; ...
    "Exact V1 reproduction; fixed date was not selected by V2"; ...
    "Sensitivity excludes predeclared 2020 Q2-Q3 collapse/rebound quarters"; ...
    search.InferenceCaveat; ...
    "Brown-Durbin-Evans recursive-residual boundary; parameter constancy null"; ...
    "Conditional iid-Gaussian Monte Carlo band; especially outlier-sensitive"];
tests = table(Test,Scope,Statistic,ReferenceThreshold,PointwisePValue, ...
    GlobalOrBootstrapPValue,RejectAt5Percent,SampleSize,BreakDate, ...
    UncertaintyStart,UncertaintyEnd,ExPostOnly,Caveat);
end

function summary = buildRegimeSummary(fixed,sensitivity,search,X,Y,protocol)
selectedPre = macro.estimateOLS(X(1:search.BestSplit,:), ...
    Y(1:search.BestSplit),CovarianceSolver="inverse");
selectedPost = macro.estimateOLS(X(search.BestSplit+1:end,:), ...
    Y(search.BestSplit+1:end),CovarianceSolver="inverse");
Analysis = ["V1 fixed baseline";"V1 fixed baseline"; ...
    "V2 fixed-date reproduction";"V2 fixed-date reproduction"; ...
    "V2 acute-COVID sensitivity";"V2 acute-COVID sensitivity"; ...
    "V2 selected single break";"V2 selected single break"];
Regime = repmat(["Before break";"On/after break"],4,1);
BreakDate = repelem([fixed.BreakDate;fixed.BreakDate; ...
    sensitivity.BreakDate;search.BreakDate],2);
Observations = [fixed.PreObservations;fixed.PostObservations; ...
    fixed.PreObservations;fixed.PostObservations; ...
    sensitivity.PreObservations;sensitivity.PostObservations; ...
    search.BestSplit;fixed.PooledModel.Observations-search.BestSplit];
RSquared = [fixed.PreModel.RSquared;fixed.PostModel.RSquared; ...
    fixed.PreModel.RSquared;fixed.PostModel.RSquared; ...
    sensitivity.PreModel.RSquared;sensitivity.PostModel.RSquared; ...
    selectedPre.RSquared;selectedPost.RSquared];
AdjustedRSquared = [fixed.PreModel.AdjustedRSquared; ...
    fixed.PostModel.AdjustedRSquared;fixed.PreModel.AdjustedRSquared; ...
    fixed.PostModel.AdjustedRSquared;sensitivity.PreModel.AdjustedRSquared; ...
    sensitivity.PostModel.AdjustedRSquared;selectedPre.AdjustedRSquared; ...
    selectedPost.AdjustedRSquared];
RMSE = [fixed.PreModel.RMSE;fixed.PostModel.RMSE;fixed.PreModel.RMSE; ...
    fixed.PostModel.RMSE;sensitivity.PreModel.RMSE; ...
    sensitivity.PostModel.RMSE;selectedPre.RMSE;selectedPost.RMSE];
AcuteCOVIDQuartersExcluded = [false(4,1);true(2,1);false(2,1)];
ExPostOnly = [false(2,1);true(6,1)];
Interpretation = [repmat("Preserved V1 baseline",2,1); ...
    repmat("Ex-post reproduction; not a forecast input",2,1); ...
    repmat("Ex-post acute-shock sensitivity; not causal",2,1); ...
    repmat("Ex-post selected break; subject to post-selection uncertainty",2,1)];
summary = table(Analysis,Regime,BreakDate,Observations,RSquared, ...
    AdjustedRSquared,RMSE,AcuteCOVIDQuartersExcluded,ExPostOnly,Interpretation);
end

function files = createFigures(cfg,design,recursive,search)
residuals = recursive.ResidualDiagnostics;

fig1=figure("Visible","off","Position",[100 100 1100 550]);
plot(residuals.Date,residuals.CUSUM,"LineWidth",1.4); hold on;
plot(residuals.Date,residuals.CUSUMUpper,"--","LineWidth",1.1);
plot(residuals.Date,residuals.CUSUMLower,"--","LineWidth",1.1);
yline(0,":"); grid on; title("V2 CUSUM Stability Diagnostic");
ylabel("Cumulative standardized recursive residual");
legend("CUSUM","5% upper boundary","5% lower boundary","Location","best");
cusumPath=fullfile(cfg.FiguresDir,"V2_CUSUM.png");
exportgraphics(fig1,cusumPath,"Resolution",200); close(fig1);

fig2=figure("Visible","off","Position",[100 100 1100 550]);
plot(residuals.Date,residuals.CUSUMSQ,"LineWidth",1.4); hold on;
plot(residuals.Date,residuals.CUSUMSQUpper,"--","LineWidth",1.1);
plot(residuals.Date,residuals.CUSUMSQLower,"--","LineWidth",1.1);
grid on; title("V2 CUSUMSQ Sensitivity Diagnostic");
ylabel("Cumulative share of squared recursive residuals");
legend("CUSUMSQ","95% upper band","95% lower band","Location","best");
cusumsqPath=fullfile(cfg.FiguresDir,"V2_CUSUMSQ.png");
exportgraphics(fig2,cusumsqPath,"Resolution",200); close(fig2);

paths=recursive.CoefficientPaths;
fig3=figure("Visible","off","Position",[100 100 1400 900]);
tiledlayout(4,4,"TileSpacing","compact");
for variableIndex=1:numel(design.VariableNames)
    nexttile;
    selected=paths.Variable==design.VariableNames(variableIndex);
    plot(paths.EndDate(selected),paths.Coefficient(selected),"LineWidth",1);
    title(strrep(design.VariableNames(variableIndex),"_"," "));
    grid on;
end
coefficientPath=fullfile(cfg.FiguresDir,"V2_Recursive_Coefficient_Paths.png");
exportgraphics(fig3,coefficientPath,"Resolution",200); close(fig3);

fig4=figure("Visible","off","Position",[100 100 1150 550]);
plot(search.CandidateTable.CandidateBreakDate, ...
    search.CandidateTable.WaldFStatistic,"LineWidth",1.5); hold on;
xline(search.BreakDate,"--","Maximum","LineWidth",1.2);
grid on; title("V2 Trimmed Single-Break Wald Statistic");
xlabel("Candidate break date"); ylabel("Chow/Wald F statistic");
breakPath=fullfile(cfg.FiguresDir,"V2_Sup_Wald_Break_Timeline.png");
exportgraphics(fig4,breakPath,"Resolution",200); close(fig4);
files=[cusumPath;cusumsqPath;coefficientPath;breakPath];
end
