function results = stationarityDiagnostics(series,seriesName,options)
%STATIONARITYDIAGNOSTICS Run predeclared ADF and KPSS tests for one series.

arguments
    series double
    seriesName (1,1) string
    options.ADFModel (1,1) string {mustBeMember( ...
        options.ADFModel,["AR","ARD","TS"])} = "ARD"
    options.KPSSTrend (1,1) logical = false
    options.Alpha (1,1) double {mustBeGreaterThan(options.Alpha,0), ...
        mustBeLessThan(options.Alpha,1)} = 0.05
    options.MaximumLagCap (1,1) double {mustBeInteger,mustBeNonnegative} = 8
end

if exist("adftest","file") ~= 2 || exist("kpsstest","file") ~= 2
    error("macro:v2:stationarityDiagnostics:MissingToolbox", ...
        "ADF and KPSS diagnostics require Econometrics Toolbox.");
end
if ~isvector(series) || numel(series) < 12 || ...
        ~isreal(series) || any(~isfinite(series))
    error("macro:v2:stationarityDiagnostics:InvalidSeries", ...
        "Stationarity diagnostics require at least 12 finite observations.");
end
series = series(:);
lagSelection = macro.v2.selectAdfLag(series,options.ADFModel, ...
    MaximumLagCap=options.MaximumLagCap);
kpssBandwidth = macro.v2.bandwidthRule(numel(series));
lastwarn("");
[adfReject,adfPValue,adfStatistic,adfCriticalValue] = adftest( ...
    series,Model=options.ADFModel,Lags=lagSelection.SelectedLag, ...
    Alpha=options.Alpha);
[adfWarningMessage,adfWarningID] = lastwarn;
adfValid = string(adfWarningID) ~= "econ:adftest:InvalidStatistic";
adfDiagnostic = strip(regexprep(string(adfWarningMessage),"\s+"," "));
[kpssReject,kpssPValue,kpssStatistic,kpssCriticalValue] = kpsstest( ...
    series,Trend=options.KPSSTrend,Lags=kpssBandwidth, ...
    Alpha=options.Alpha);

if ~adfValid
    conclusion = "Ambiguous";
elseif adfReject && ~kpssReject
    conclusion = "Stationary";
elseif ~adfReject && kpssReject
    conclusion = "Nonstationary";
else
    conclusion = "Ambiguous";
end

results = struct( ...
    "Series",seriesName, ...
    "Observations",numel(series), ...
    "ADFModel",options.ADFModel, ...
    "ADFSelectedLag",lagSelection.SelectedLag, ...
    "ADFMaximumLag",lagSelection.MaximumLag, ...
    "ADFStatistic",adfStatistic, ...
    "ADFCriticalValue",adfCriticalValue, ...
    "ADFPValue",adfPValue, ...
    "ADFRejectUnitRoot",logical(adfReject), ...
    "ADFValid",adfValid, ...
    "ADFDiagnostic",adfDiagnostic, ...
    "KPSSTrend",options.KPSSTrend, ...
    "KPSSBandwidth",kpssBandwidth, ...
    "KPSSStatistic",kpssStatistic, ...
    "KPSSCriticalValue",kpssCriticalValue, ...
    "KPSSPValue",kpssPValue, ...
    "KPSSRejectStationarity",logical(kpssReject), ...
    "Alpha",options.Alpha, ...
    "Conclusion",conclusion, ...
    "LagSelection",lagSelection);
end
