function protocol = structuralStabilityProtocol()
%STRUCTURALSTABILITYPROTOCOL Predeclared V2.6 stability diagnostics.
%   These settings define an ex-post diagnostic exercise. Detected breaks
%   are never inputs to the V2 forecasting or model-selection pipelines.

protocol = struct( ...
    "AnalysisScope","Ex-post full-sample structural diagnostic", ...
    "ForecastUseProhibited",true, ...
    "V1BaselineBreakDate",datetime(2020,1,1), ...
    "CandidateTrimFraction",0.15, ...
    "MinimumExtraRegimeObservations",5, ...
    "RecursiveCoefficientMinimumObservations",40, ...
    "CUSUMAlpha",0.05, ...
    "CUSUMBoundaryConstant",0.948, ...
    "CUSUMSQAlpha",0.05, ...
    "CUSUMSQSimulationReplications",5000, ...
    "CUSUMSQSimulationSeed",2606, ...
    "BreakBootstrapReplications",499, ...
    "BreakBootstrapBlockLength",4, ...
    "BreakBootstrapSeed",2610, ...
    "BreakConfidenceLevel",0.95, ...
    "AcuteCOVIDStart",datetime(2020,4,1), ...
    "AcuteCOVIDEnd",datetime(2020,7,1), ...
    "MultipleBreakAnalysisImplemented",false, ...
    "MultipleBreakReason", ...
    "Omitted: the 14-parameter design and short post-2020 regime do not support defensible multiple-break estimation.");
end
