function pair = validateForecastPair(modelForecasts,benchmarkForecasts)
%VALIDATEFORECASTPAIR Require identical dates and actuals for comparison.

arguments
    modelForecasts table
    benchmarkForecasts table
end

required = ["TargetQuarter","ActualGDPGrowth","Forecast"];
macro.requireTableVariables(modelForecasts,required,DataName="model forecasts");
macro.requireTableVariables(benchmarkForecasts,required, ...
    DataName="benchmark forecasts");
if height(modelForecasts) ~= height(benchmarkForecasts) || ...
        ~isequal(modelForecasts.TargetQuarter,benchmarkForecasts.TargetQuarter)
    error("macro:v2:validateForecastPair:MismatchedDates", ...
        "Formal forecast comparisons require identical ordered dates.");
end
if ~isdatetime(modelForecasts.TargetQuarter) || ...
        any(isnat(modelForecasts.TargetQuarter)) || ...
        any(modelForecasts.TargetQuarter(2:end) <= ...
        modelForecasts.TargetQuarter(1:end-1))
    error("macro:v2:validateForecastPair:InvalidDates", ...
        "Forecast dates must be unique, valid, and strictly increasing.");
end
numericNames = ["ActualGDPGrowth","Forecast"];
for name = numericNames
    if ~isnumeric(modelForecasts.(name)) || ...
            any(~isfinite(modelForecasts.(name))) || ...
            ~isnumeric(benchmarkForecasts.(name)) || ...
            any(~isfinite(benchmarkForecasts.(name)))
        error("macro:v2:validateForecastPair:InvalidValues", ...
            "Forecast comparisons require finite numeric actuals and forecasts.");
    end
end
if ~isequaln(modelForecasts.ActualGDPGrowth, ...
        benchmarkForecasts.ActualGDPGrowth)
    error("macro:v2:validateForecastPair:MismatchedActuals", ...
        "Forecast comparisons require identical realized targets.");
end

pair = struct( ...
    "Dates",modelForecasts.TargetQuarter, ...
    "Actual",modelForecasts.ActualGDPGrowth(:), ...
    "ModelForecast",modelForecasts.Forecast(:), ...
    "BenchmarkForecast",benchmarkForecasts.Forecast(:), ...
    "Observations",height(modelForecasts));
end
